-- -------------------------------------------------------------
--
-- Module: rx_hilb
-- Generated by MATLAB(R) 9.6 and Filter Design HDL Coder 3.1.5.
-- Generated on: 2019-05-19 13:35:49
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- OptimizeForHDL: on
-- EDAScriptGeneration: off
-- Name: rx_hilb
-- SerialPartition: 256
-- TestBenchName: rx_hilb_tb
-- TestBenchStimulus: impulse step ramp chirp noise 
-- GenerateHDLTestBench: off

-- Filter Specifications:
--
-- Sample Rate      : N/A (normalized frequency)
-- Response         : Hilbert Transformer
-- Specification    : TW,Ap
-- Transition Width : 0.029
-- Passband Ripple  : 0.017 dB
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully Serial
-- Folding Factor        : 256
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 256
-- Stable            : Yes
-- Linear Phase      : Yes (Type 4)
-- Arithmetic        : fixed
-- Numerator         : s16,15 -> [-1 1)
-- Input             : s16,15 -> [-1 1)
-- Filter Internals  : Specify Precision
--   Output          : s16,15 -> [-1 1)
--   Product         : s32,29 -> [-4 4)
--   Accumulator     : s40,29 -> [-1024 1024)
--   Round Mode      : convergent
--   Overflow Mode   : wrap
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY rx_hilb IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(15 DOWNTO 0); -- sfix16_En15
         filter_out                      :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
         );

END rx_hilb;


----------------------------------------------------------------
--Module Architecture: rx_hilb
----------------------------------------------------------------
ARCHITECTURE rtl OF rx_hilb IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(15 DOWNTO 0); -- sfix16_En15
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(-18, 16); -- sfix16_En15
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(-1, 16); -- sfix16_En15
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(-6, 16); -- sfix16_En15
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(-1, 16); -- sfix16_En15
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(-7, 16); -- sfix16_En15
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(-2, 16); -- sfix16_En15
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(-8, 16); -- sfix16_En15
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(-2, 16); -- sfix16_En15
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(-9, 16); -- sfix16_En15
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(-2, 16); -- sfix16_En15
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(-10, 16); -- sfix16_En15
  CONSTANT coeff12                        : signed(15 DOWNTO 0) := to_signed(-3, 16); -- sfix16_En15
  CONSTANT coeff13                        : signed(15 DOWNTO 0) := to_signed(-11, 16); -- sfix16_En15
  CONSTANT coeff14                        : signed(15 DOWNTO 0) := to_signed(-4, 16); -- sfix16_En15
  CONSTANT coeff15                        : signed(15 DOWNTO 0) := to_signed(-13, 16); -- sfix16_En15
  CONSTANT coeff16                        : signed(15 DOWNTO 0) := to_signed(-4, 16); -- sfix16_En15
  CONSTANT coeff17                        : signed(15 DOWNTO 0) := to_signed(-14, 16); -- sfix16_En15
  CONSTANT coeff18                        : signed(15 DOWNTO 0) := to_signed(-5, 16); -- sfix16_En15
  CONSTANT coeff19                        : signed(15 DOWNTO 0) := to_signed(-16, 16); -- sfix16_En15
  CONSTANT coeff20                        : signed(15 DOWNTO 0) := to_signed(-6, 16); -- sfix16_En15
  CONSTANT coeff21                        : signed(15 DOWNTO 0) := to_signed(-18, 16); -- sfix16_En15
  CONSTANT coeff22                        : signed(15 DOWNTO 0) := to_signed(-7, 16); -- sfix16_En15
  CONSTANT coeff23                        : signed(15 DOWNTO 0) := to_signed(-20, 16); -- sfix16_En15
  CONSTANT coeff24                        : signed(15 DOWNTO 0) := to_signed(-8, 16); -- sfix16_En15
  CONSTANT coeff25                        : signed(15 DOWNTO 0) := to_signed(-22, 16); -- sfix16_En15
  CONSTANT coeff26                        : signed(15 DOWNTO 0) := to_signed(-9, 16); -- sfix16_En15
  CONSTANT coeff27                        : signed(15 DOWNTO 0) := to_signed(-24, 16); -- sfix16_En15
  CONSTANT coeff28                        : signed(15 DOWNTO 0) := to_signed(-10, 16); -- sfix16_En15
  CONSTANT coeff29                        : signed(15 DOWNTO 0) := to_signed(-26, 16); -- sfix16_En15
  CONSTANT coeff30                        : signed(15 DOWNTO 0) := to_signed(-11, 16); -- sfix16_En15
  CONSTANT coeff31                        : signed(15 DOWNTO 0) := to_signed(-29, 16); -- sfix16_En15
  CONSTANT coeff32                        : signed(15 DOWNTO 0) := to_signed(-13, 16); -- sfix16_En15
  CONSTANT coeff33                        : signed(15 DOWNTO 0) := to_signed(-32, 16); -- sfix16_En15
  CONSTANT coeff34                        : signed(15 DOWNTO 0) := to_signed(-15, 16); -- sfix16_En15
  CONSTANT coeff35                        : signed(15 DOWNTO 0) := to_signed(-35, 16); -- sfix16_En15
  CONSTANT coeff36                        : signed(15 DOWNTO 0) := to_signed(-16, 16); -- sfix16_En15
  CONSTANT coeff37                        : signed(15 DOWNTO 0) := to_signed(-38, 16); -- sfix16_En15
  CONSTANT coeff38                        : signed(15 DOWNTO 0) := to_signed(-18, 16); -- sfix16_En15
  CONSTANT coeff39                        : signed(15 DOWNTO 0) := to_signed(-41, 16); -- sfix16_En15
  CONSTANT coeff40                        : signed(15 DOWNTO 0) := to_signed(-20, 16); -- sfix16_En15
  CONSTANT coeff41                        : signed(15 DOWNTO 0) := to_signed(-45, 16); -- sfix16_En15
  CONSTANT coeff42                        : signed(15 DOWNTO 0) := to_signed(-23, 16); -- sfix16_En15
  CONSTANT coeff43                        : signed(15 DOWNTO 0) := to_signed(-48, 16); -- sfix16_En15
  CONSTANT coeff44                        : signed(15 DOWNTO 0) := to_signed(-25, 16); -- sfix16_En15
  CONSTANT coeff45                        : signed(15 DOWNTO 0) := to_signed(-52, 16); -- sfix16_En15
  CONSTANT coeff46                        : signed(15 DOWNTO 0) := to_signed(-28, 16); -- sfix16_En15
  CONSTANT coeff47                        : signed(15 DOWNTO 0) := to_signed(-56, 16); -- sfix16_En15
  CONSTANT coeff48                        : signed(15 DOWNTO 0) := to_signed(-31, 16); -- sfix16_En15
  CONSTANT coeff49                        : signed(15 DOWNTO 0) := to_signed(-61, 16); -- sfix16_En15
  CONSTANT coeff50                        : signed(15 DOWNTO 0) := to_signed(-34, 16); -- sfix16_En15
  CONSTANT coeff51                        : signed(15 DOWNTO 0) := to_signed(-66, 16); -- sfix16_En15
  CONSTANT coeff52                        : signed(15 DOWNTO 0) := to_signed(-37, 16); -- sfix16_En15
  CONSTANT coeff53                        : signed(15 DOWNTO 0) := to_signed(-71, 16); -- sfix16_En15
  CONSTANT coeff54                        : signed(15 DOWNTO 0) := to_signed(-41, 16); -- sfix16_En15
  CONSTANT coeff55                        : signed(15 DOWNTO 0) := to_signed(-76, 16); -- sfix16_En15
  CONSTANT coeff56                        : signed(15 DOWNTO 0) := to_signed(-45, 16); -- sfix16_En15
  CONSTANT coeff57                        : signed(15 DOWNTO 0) := to_signed(-81, 16); -- sfix16_En15
  CONSTANT coeff58                        : signed(15 DOWNTO 0) := to_signed(-49, 16); -- sfix16_En15
  CONSTANT coeff59                        : signed(15 DOWNTO 0) := to_signed(-87, 16); -- sfix16_En15
  CONSTANT coeff60                        : signed(15 DOWNTO 0) := to_signed(-54, 16); -- sfix16_En15
  CONSTANT coeff61                        : signed(15 DOWNTO 0) := to_signed(-94, 16); -- sfix16_En15
  CONSTANT coeff62                        : signed(15 DOWNTO 0) := to_signed(-58, 16); -- sfix16_En15
  CONSTANT coeff63                        : signed(15 DOWNTO 0) := to_signed(-100, 16); -- sfix16_En15
  CONSTANT coeff64                        : signed(15 DOWNTO 0) := to_signed(-64, 16); -- sfix16_En15
  CONSTANT coeff65                        : signed(15 DOWNTO 0) := to_signed(-107, 16); -- sfix16_En15
  CONSTANT coeff66                        : signed(15 DOWNTO 0) := to_signed(-69, 16); -- sfix16_En15
  CONSTANT coeff67                        : signed(15 DOWNTO 0) := to_signed(-115, 16); -- sfix16_En15
  CONSTANT coeff68                        : signed(15 DOWNTO 0) := to_signed(-75, 16); -- sfix16_En15
  CONSTANT coeff69                        : signed(15 DOWNTO 0) := to_signed(-122, 16); -- sfix16_En15
  CONSTANT coeff70                        : signed(15 DOWNTO 0) := to_signed(-82, 16); -- sfix16_En15
  CONSTANT coeff71                        : signed(15 DOWNTO 0) := to_signed(-131, 16); -- sfix16_En15
  CONSTANT coeff72                        : signed(15 DOWNTO 0) := to_signed(-89, 16); -- sfix16_En15
  CONSTANT coeff73                        : signed(15 DOWNTO 0) := to_signed(-140, 16); -- sfix16_En15
  CONSTANT coeff74                        : signed(15 DOWNTO 0) := to_signed(-97, 16); -- sfix16_En15
  CONSTANT coeff75                        : signed(15 DOWNTO 0) := to_signed(-149, 16); -- sfix16_En15
  CONSTANT coeff76                        : signed(15 DOWNTO 0) := to_signed(-105, 16); -- sfix16_En15
  CONSTANT coeff77                        : signed(15 DOWNTO 0) := to_signed(-159, 16); -- sfix16_En15
  CONSTANT coeff78                        : signed(15 DOWNTO 0) := to_signed(-114, 16); -- sfix16_En15
  CONSTANT coeff79                        : signed(15 DOWNTO 0) := to_signed(-170, 16); -- sfix16_En15
  CONSTANT coeff80                        : signed(15 DOWNTO 0) := to_signed(-123, 16); -- sfix16_En15
  CONSTANT coeff81                        : signed(15 DOWNTO 0) := to_signed(-181, 16); -- sfix16_En15
  CONSTANT coeff82                        : signed(15 DOWNTO 0) := to_signed(-134, 16); -- sfix16_En15
  CONSTANT coeff83                        : signed(15 DOWNTO 0) := to_signed(-194, 16); -- sfix16_En15
  CONSTANT coeff84                        : signed(15 DOWNTO 0) := to_signed(-145, 16); -- sfix16_En15
  CONSTANT coeff85                        : signed(15 DOWNTO 0) := to_signed(-207, 16); -- sfix16_En15
  CONSTANT coeff86                        : signed(15 DOWNTO 0) := to_signed(-158, 16); -- sfix16_En15
  CONSTANT coeff87                        : signed(15 DOWNTO 0) := to_signed(-221, 16); -- sfix16_En15
  CONSTANT coeff88                        : signed(15 DOWNTO 0) := to_signed(-172, 16); -- sfix16_En15
  CONSTANT coeff89                        : signed(15 DOWNTO 0) := to_signed(-237, 16); -- sfix16_En15
  CONSTANT coeff90                        : signed(15 DOWNTO 0) := to_signed(-187, 16); -- sfix16_En15
  CONSTANT coeff91                        : signed(15 DOWNTO 0) := to_signed(-254, 16); -- sfix16_En15
  CONSTANT coeff92                        : signed(15 DOWNTO 0) := to_signed(-203, 16); -- sfix16_En15
  CONSTANT coeff93                        : signed(15 DOWNTO 0) := to_signed(-273, 16); -- sfix16_En15
  CONSTANT coeff94                        : signed(15 DOWNTO 0) := to_signed(-222, 16); -- sfix16_En15
  CONSTANT coeff95                        : signed(15 DOWNTO 0) := to_signed(-293, 16); -- sfix16_En15
  CONSTANT coeff96                        : signed(15 DOWNTO 0) := to_signed(-242, 16); -- sfix16_En15
  CONSTANT coeff97                        : signed(15 DOWNTO 0) := to_signed(-316, 16); -- sfix16_En15
  CONSTANT coeff98                        : signed(15 DOWNTO 0) := to_signed(-265, 16); -- sfix16_En15
  CONSTANT coeff99                        : signed(15 DOWNTO 0) := to_signed(-342, 16); -- sfix16_En15
  CONSTANT coeff100                       : signed(15 DOWNTO 0) := to_signed(-291, 16); -- sfix16_En15
  CONSTANT coeff101                       : signed(15 DOWNTO 0) := to_signed(-371, 16); -- sfix16_En15
  CONSTANT coeff102                       : signed(15 DOWNTO 0) := to_signed(-321, 16); -- sfix16_En15
  CONSTANT coeff103                       : signed(15 DOWNTO 0) := to_signed(-404, 16); -- sfix16_En15
  CONSTANT coeff104                       : signed(15 DOWNTO 0) := to_signed(-356, 16); -- sfix16_En15
  CONSTANT coeff105                       : signed(15 DOWNTO 0) := to_signed(-442, 16); -- sfix16_En15
  CONSTANT coeff106                       : signed(15 DOWNTO 0) := to_signed(-396, 16); -- sfix16_En15
  CONSTANT coeff107                       : signed(15 DOWNTO 0) := to_signed(-486, 16); -- sfix16_En15
  CONSTANT coeff108                       : signed(15 DOWNTO 0) := to_signed(-444, 16); -- sfix16_En15
  CONSTANT coeff109                       : signed(15 DOWNTO 0) := to_signed(-539, 16); -- sfix16_En15
  CONSTANT coeff110                       : signed(15 DOWNTO 0) := to_signed(-501, 16); -- sfix16_En15
  CONSTANT coeff111                       : signed(15 DOWNTO 0) := to_signed(-604, 16); -- sfix16_En15
  CONSTANT coeff112                       : signed(15 DOWNTO 0) := to_signed(-572, 16); -- sfix16_En15
  CONSTANT coeff113                       : signed(15 DOWNTO 0) := to_signed(-684, 16); -- sfix16_En15
  CONSTANT coeff114                       : signed(15 DOWNTO 0) := to_signed(-662, 16); -- sfix16_En15
  CONSTANT coeff115                       : signed(15 DOWNTO 0) := to_signed(-787, 16); -- sfix16_En15
  CONSTANT coeff116                       : signed(15 DOWNTO 0) := to_signed(-780, 16); -- sfix16_En15
  CONSTANT coeff117                       : signed(15 DOWNTO 0) := to_signed(-924, 16); -- sfix16_En15
  CONSTANT coeff118                       : signed(15 DOWNTO 0) := to_signed(-942, 16); -- sfix16_En15
  CONSTANT coeff119                       : signed(15 DOWNTO 0) := to_signed(-1119, 16); -- sfix16_En15
  CONSTANT coeff120                       : signed(15 DOWNTO 0) := to_signed(-1178, 16); -- sfix16_En15
  CONSTANT coeff121                       : signed(15 DOWNTO 0) := to_signed(-1415, 16); -- sfix16_En15
  CONSTANT coeff122                       : signed(15 DOWNTO 0) := to_signed(-1559, 16); -- sfix16_En15
  CONSTANT coeff123                       : signed(15 DOWNTO 0) := to_signed(-1924, 16); -- sfix16_En15
  CONSTANT coeff124                       : signed(15 DOWNTO 0) := to_signed(-2275, 16); -- sfix16_En15
  CONSTANT coeff125                       : signed(15 DOWNTO 0) := to_signed(-3011, 16); -- sfix16_En15
  CONSTANT coeff126                       : signed(15 DOWNTO 0) := to_signed(-4132, 16); -- sfix16_En15
  CONSTANT coeff127                       : signed(15 DOWNTO 0) := to_signed(-6987, 16); -- sfix16_En15
  CONSTANT coeff128                       : signed(15 DOWNTO 0) := to_signed(-20824, 16); -- sfix16_En15
  CONSTANT coeff129                       : signed(15 DOWNTO 0) := to_signed(20824, 16); -- sfix16_En15
  CONSTANT coeff130                       : signed(15 DOWNTO 0) := to_signed(6987, 16); -- sfix16_En15
  CONSTANT coeff131                       : signed(15 DOWNTO 0) := to_signed(4132, 16); -- sfix16_En15
  CONSTANT coeff132                       : signed(15 DOWNTO 0) := to_signed(3011, 16); -- sfix16_En15
  CONSTANT coeff133                       : signed(15 DOWNTO 0) := to_signed(2275, 16); -- sfix16_En15
  CONSTANT coeff134                       : signed(15 DOWNTO 0) := to_signed(1924, 16); -- sfix16_En15
  CONSTANT coeff135                       : signed(15 DOWNTO 0) := to_signed(1559, 16); -- sfix16_En15
  CONSTANT coeff136                       : signed(15 DOWNTO 0) := to_signed(1415, 16); -- sfix16_En15
  CONSTANT coeff137                       : signed(15 DOWNTO 0) := to_signed(1178, 16); -- sfix16_En15
  CONSTANT coeff138                       : signed(15 DOWNTO 0) := to_signed(1119, 16); -- sfix16_En15
  CONSTANT coeff139                       : signed(15 DOWNTO 0) := to_signed(942, 16); -- sfix16_En15
  CONSTANT coeff140                       : signed(15 DOWNTO 0) := to_signed(924, 16); -- sfix16_En15
  CONSTANT coeff141                       : signed(15 DOWNTO 0) := to_signed(780, 16); -- sfix16_En15
  CONSTANT coeff142                       : signed(15 DOWNTO 0) := to_signed(787, 16); -- sfix16_En15
  CONSTANT coeff143                       : signed(15 DOWNTO 0) := to_signed(662, 16); -- sfix16_En15
  CONSTANT coeff144                       : signed(15 DOWNTO 0) := to_signed(684, 16); -- sfix16_En15
  CONSTANT coeff145                       : signed(15 DOWNTO 0) := to_signed(572, 16); -- sfix16_En15
  CONSTANT coeff146                       : signed(15 DOWNTO 0) := to_signed(604, 16); -- sfix16_En15
  CONSTANT coeff147                       : signed(15 DOWNTO 0) := to_signed(501, 16); -- sfix16_En15
  CONSTANT coeff148                       : signed(15 DOWNTO 0) := to_signed(539, 16); -- sfix16_En15
  CONSTANT coeff149                       : signed(15 DOWNTO 0) := to_signed(444, 16); -- sfix16_En15
  CONSTANT coeff150                       : signed(15 DOWNTO 0) := to_signed(486, 16); -- sfix16_En15
  CONSTANT coeff151                       : signed(15 DOWNTO 0) := to_signed(396, 16); -- sfix16_En15
  CONSTANT coeff152                       : signed(15 DOWNTO 0) := to_signed(442, 16); -- sfix16_En15
  CONSTANT coeff153                       : signed(15 DOWNTO 0) := to_signed(356, 16); -- sfix16_En15
  CONSTANT coeff154                       : signed(15 DOWNTO 0) := to_signed(404, 16); -- sfix16_En15
  CONSTANT coeff155                       : signed(15 DOWNTO 0) := to_signed(321, 16); -- sfix16_En15
  CONSTANT coeff156                       : signed(15 DOWNTO 0) := to_signed(371, 16); -- sfix16_En15
  CONSTANT coeff157                       : signed(15 DOWNTO 0) := to_signed(291, 16); -- sfix16_En15
  CONSTANT coeff158                       : signed(15 DOWNTO 0) := to_signed(342, 16); -- sfix16_En15
  CONSTANT coeff159                       : signed(15 DOWNTO 0) := to_signed(265, 16); -- sfix16_En15
  CONSTANT coeff160                       : signed(15 DOWNTO 0) := to_signed(316, 16); -- sfix16_En15
  CONSTANT coeff161                       : signed(15 DOWNTO 0) := to_signed(242, 16); -- sfix16_En15
  CONSTANT coeff162                       : signed(15 DOWNTO 0) := to_signed(293, 16); -- sfix16_En15
  CONSTANT coeff163                       : signed(15 DOWNTO 0) := to_signed(222, 16); -- sfix16_En15
  CONSTANT coeff164                       : signed(15 DOWNTO 0) := to_signed(273, 16); -- sfix16_En15
  CONSTANT coeff165                       : signed(15 DOWNTO 0) := to_signed(203, 16); -- sfix16_En15
  CONSTANT coeff166                       : signed(15 DOWNTO 0) := to_signed(254, 16); -- sfix16_En15
  CONSTANT coeff167                       : signed(15 DOWNTO 0) := to_signed(187, 16); -- sfix16_En15
  CONSTANT coeff168                       : signed(15 DOWNTO 0) := to_signed(237, 16); -- sfix16_En15
  CONSTANT coeff169                       : signed(15 DOWNTO 0) := to_signed(172, 16); -- sfix16_En15
  CONSTANT coeff170                       : signed(15 DOWNTO 0) := to_signed(221, 16); -- sfix16_En15
  CONSTANT coeff171                       : signed(15 DOWNTO 0) := to_signed(158, 16); -- sfix16_En15
  CONSTANT coeff172                       : signed(15 DOWNTO 0) := to_signed(207, 16); -- sfix16_En15
  CONSTANT coeff173                       : signed(15 DOWNTO 0) := to_signed(145, 16); -- sfix16_En15
  CONSTANT coeff174                       : signed(15 DOWNTO 0) := to_signed(194, 16); -- sfix16_En15
  CONSTANT coeff175                       : signed(15 DOWNTO 0) := to_signed(134, 16); -- sfix16_En15
  CONSTANT coeff176                       : signed(15 DOWNTO 0) := to_signed(181, 16); -- sfix16_En15
  CONSTANT coeff177                       : signed(15 DOWNTO 0) := to_signed(123, 16); -- sfix16_En15
  CONSTANT coeff178                       : signed(15 DOWNTO 0) := to_signed(170, 16); -- sfix16_En15
  CONSTANT coeff179                       : signed(15 DOWNTO 0) := to_signed(114, 16); -- sfix16_En15
  CONSTANT coeff180                       : signed(15 DOWNTO 0) := to_signed(159, 16); -- sfix16_En15
  CONSTANT coeff181                       : signed(15 DOWNTO 0) := to_signed(105, 16); -- sfix16_En15
  CONSTANT coeff182                       : signed(15 DOWNTO 0) := to_signed(149, 16); -- sfix16_En15
  CONSTANT coeff183                       : signed(15 DOWNTO 0) := to_signed(97, 16); -- sfix16_En15
  CONSTANT coeff184                       : signed(15 DOWNTO 0) := to_signed(140, 16); -- sfix16_En15
  CONSTANT coeff185                       : signed(15 DOWNTO 0) := to_signed(89, 16); -- sfix16_En15
  CONSTANT coeff186                       : signed(15 DOWNTO 0) := to_signed(131, 16); -- sfix16_En15
  CONSTANT coeff187                       : signed(15 DOWNTO 0) := to_signed(82, 16); -- sfix16_En15
  CONSTANT coeff188                       : signed(15 DOWNTO 0) := to_signed(122, 16); -- sfix16_En15
  CONSTANT coeff189                       : signed(15 DOWNTO 0) := to_signed(75, 16); -- sfix16_En15
  CONSTANT coeff190                       : signed(15 DOWNTO 0) := to_signed(115, 16); -- sfix16_En15
  CONSTANT coeff191                       : signed(15 DOWNTO 0) := to_signed(69, 16); -- sfix16_En15
  CONSTANT coeff192                       : signed(15 DOWNTO 0) := to_signed(107, 16); -- sfix16_En15
  CONSTANT coeff193                       : signed(15 DOWNTO 0) := to_signed(64, 16); -- sfix16_En15
  CONSTANT coeff194                       : signed(15 DOWNTO 0) := to_signed(100, 16); -- sfix16_En15
  CONSTANT coeff195                       : signed(15 DOWNTO 0) := to_signed(58, 16); -- sfix16_En15
  CONSTANT coeff196                       : signed(15 DOWNTO 0) := to_signed(94, 16); -- sfix16_En15
  CONSTANT coeff197                       : signed(15 DOWNTO 0) := to_signed(54, 16); -- sfix16_En15
  CONSTANT coeff198                       : signed(15 DOWNTO 0) := to_signed(87, 16); -- sfix16_En15
  CONSTANT coeff199                       : signed(15 DOWNTO 0) := to_signed(49, 16); -- sfix16_En15
  CONSTANT coeff200                       : signed(15 DOWNTO 0) := to_signed(81, 16); -- sfix16_En15
  CONSTANT coeff201                       : signed(15 DOWNTO 0) := to_signed(45, 16); -- sfix16_En15
  CONSTANT coeff202                       : signed(15 DOWNTO 0) := to_signed(76, 16); -- sfix16_En15
  CONSTANT coeff203                       : signed(15 DOWNTO 0) := to_signed(41, 16); -- sfix16_En15
  CONSTANT coeff204                       : signed(15 DOWNTO 0) := to_signed(71, 16); -- sfix16_En15
  CONSTANT coeff205                       : signed(15 DOWNTO 0) := to_signed(37, 16); -- sfix16_En15
  CONSTANT coeff206                       : signed(15 DOWNTO 0) := to_signed(66, 16); -- sfix16_En15
  CONSTANT coeff207                       : signed(15 DOWNTO 0) := to_signed(34, 16); -- sfix16_En15
  CONSTANT coeff208                       : signed(15 DOWNTO 0) := to_signed(61, 16); -- sfix16_En15
  CONSTANT coeff209                       : signed(15 DOWNTO 0) := to_signed(31, 16); -- sfix16_En15
  CONSTANT coeff210                       : signed(15 DOWNTO 0) := to_signed(56, 16); -- sfix16_En15
  CONSTANT coeff211                       : signed(15 DOWNTO 0) := to_signed(28, 16); -- sfix16_En15
  CONSTANT coeff212                       : signed(15 DOWNTO 0) := to_signed(52, 16); -- sfix16_En15
  CONSTANT coeff213                       : signed(15 DOWNTO 0) := to_signed(25, 16); -- sfix16_En15
  CONSTANT coeff214                       : signed(15 DOWNTO 0) := to_signed(48, 16); -- sfix16_En15
  CONSTANT coeff215                       : signed(15 DOWNTO 0) := to_signed(23, 16); -- sfix16_En15
  CONSTANT coeff216                       : signed(15 DOWNTO 0) := to_signed(45, 16); -- sfix16_En15
  CONSTANT coeff217                       : signed(15 DOWNTO 0) := to_signed(20, 16); -- sfix16_En15
  CONSTANT coeff218                       : signed(15 DOWNTO 0) := to_signed(41, 16); -- sfix16_En15
  CONSTANT coeff219                       : signed(15 DOWNTO 0) := to_signed(18, 16); -- sfix16_En15
  CONSTANT coeff220                       : signed(15 DOWNTO 0) := to_signed(38, 16); -- sfix16_En15
  CONSTANT coeff221                       : signed(15 DOWNTO 0) := to_signed(16, 16); -- sfix16_En15
  CONSTANT coeff222                       : signed(15 DOWNTO 0) := to_signed(35, 16); -- sfix16_En15
  CONSTANT coeff223                       : signed(15 DOWNTO 0) := to_signed(15, 16); -- sfix16_En15
  CONSTANT coeff224                       : signed(15 DOWNTO 0) := to_signed(32, 16); -- sfix16_En15
  CONSTANT coeff225                       : signed(15 DOWNTO 0) := to_signed(13, 16); -- sfix16_En15
  CONSTANT coeff226                       : signed(15 DOWNTO 0) := to_signed(29, 16); -- sfix16_En15
  CONSTANT coeff227                       : signed(15 DOWNTO 0) := to_signed(11, 16); -- sfix16_En15
  CONSTANT coeff228                       : signed(15 DOWNTO 0) := to_signed(26, 16); -- sfix16_En15
  CONSTANT coeff229                       : signed(15 DOWNTO 0) := to_signed(10, 16); -- sfix16_En15
  CONSTANT coeff230                       : signed(15 DOWNTO 0) := to_signed(24, 16); -- sfix16_En15
  CONSTANT coeff231                       : signed(15 DOWNTO 0) := to_signed(9, 16); -- sfix16_En15
  CONSTANT coeff232                       : signed(15 DOWNTO 0) := to_signed(22, 16); -- sfix16_En15
  CONSTANT coeff233                       : signed(15 DOWNTO 0) := to_signed(8, 16); -- sfix16_En15
  CONSTANT coeff234                       : signed(15 DOWNTO 0) := to_signed(20, 16); -- sfix16_En15
  CONSTANT coeff235                       : signed(15 DOWNTO 0) := to_signed(7, 16); -- sfix16_En15
  CONSTANT coeff236                       : signed(15 DOWNTO 0) := to_signed(18, 16); -- sfix16_En15
  CONSTANT coeff237                       : signed(15 DOWNTO 0) := to_signed(6, 16); -- sfix16_En15
  CONSTANT coeff238                       : signed(15 DOWNTO 0) := to_signed(16, 16); -- sfix16_En15
  CONSTANT coeff239                       : signed(15 DOWNTO 0) := to_signed(5, 16); -- sfix16_En15
  CONSTANT coeff240                       : signed(15 DOWNTO 0) := to_signed(14, 16); -- sfix16_En15
  CONSTANT coeff241                       : signed(15 DOWNTO 0) := to_signed(4, 16); -- sfix16_En15
  CONSTANT coeff242                       : signed(15 DOWNTO 0) := to_signed(13, 16); -- sfix16_En15
  CONSTANT coeff243                       : signed(15 DOWNTO 0) := to_signed(4, 16); -- sfix16_En15
  CONSTANT coeff244                       : signed(15 DOWNTO 0) := to_signed(11, 16); -- sfix16_En15
  CONSTANT coeff245                       : signed(15 DOWNTO 0) := to_signed(3, 16); -- sfix16_En15
  CONSTANT coeff246                       : signed(15 DOWNTO 0) := to_signed(10, 16); -- sfix16_En15
  CONSTANT coeff247                       : signed(15 DOWNTO 0) := to_signed(2, 16); -- sfix16_En15
  CONSTANT coeff248                       : signed(15 DOWNTO 0) := to_signed(9, 16); -- sfix16_En15
  CONSTANT coeff249                       : signed(15 DOWNTO 0) := to_signed(2, 16); -- sfix16_En15
  CONSTANT coeff250                       : signed(15 DOWNTO 0) := to_signed(8, 16); -- sfix16_En15
  CONSTANT coeff251                       : signed(15 DOWNTO 0) := to_signed(2, 16); -- sfix16_En15
  CONSTANT coeff252                       : signed(15 DOWNTO 0) := to_signed(7, 16); -- sfix16_En15
  CONSTANT coeff253                       : signed(15 DOWNTO 0) := to_signed(1, 16); -- sfix16_En15
  CONSTANT coeff254                       : signed(15 DOWNTO 0) := to_signed(6, 16); -- sfix16_En15
  CONSTANT coeff255                       : signed(15 DOWNTO 0) := to_signed(1, 16); -- sfix16_En15
  CONSTANT coeff256                       : signed(15 DOWNTO 0) := to_signed(18, 16); -- sfix16_En15

  -- Signals
  SIGNAL cur_count                        : unsigned(7 DOWNTO 0); -- ufix8
  SIGNAL phase_255                        : std_logic; -- boolean
  SIGNAL phase_0                          : std_logic; -- boolean
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 255); -- sfix16_En15
  SIGNAL inputmux_1                       : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL acc_final                        : signed(39 DOWNTO 0); -- sfix40_En29
  SIGNAL acc_out_1                        : signed(39 DOWNTO 0); -- sfix40_En29
  SIGNAL product_1                        : signed(31 DOWNTO 0); -- sfix32_En29
  SIGNAL product_1_mux                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL mul_temp                         : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL prod_typeconvert_1               : signed(39 DOWNTO 0); -- sfix40_En29
  SIGNAL acc_sum_1                        : signed(39 DOWNTO 0); -- sfix40_En29
  SIGNAL acc_in_1                         : signed(39 DOWNTO 0); -- sfix40_En29
  SIGNAL add_temp                         : signed(40 DOWNTO 0); -- sfix41_En29
  SIGNAL output_typeconvert               : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL output_register                  : signed(15 DOWNTO 0); -- sfix16_En15


BEGIN

  -- Block Statements
  Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cur_count <= to_unsigned(255, 8);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF cur_count >= to_unsigned(255, 8) THEN
          cur_count <= to_unsigned(0, 8);
        ELSE
          cur_count <= cur_count + to_unsigned(1, 8);
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter_process;

  phase_255 <= '1' WHEN cur_count = to_unsigned(255, 8) AND clk_enable = '1' ELSE '0';

  phase_0 <= '1' WHEN cur_count = to_unsigned(0, 8) AND clk_enable = '1' ELSE '0';

  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 255) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF phase_255 = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 255) <= delay_pipeline(0 TO 254);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  inputmux_1 <= delay_pipeline(0) WHEN ( cur_count = to_unsigned(0, 8) ) ELSE
                     delay_pipeline(1) WHEN ( cur_count = to_unsigned(1, 8) ) ELSE
                     delay_pipeline(2) WHEN ( cur_count = to_unsigned(2, 8) ) ELSE
                     delay_pipeline(3) WHEN ( cur_count = to_unsigned(3, 8) ) ELSE
                     delay_pipeline(4) WHEN ( cur_count = to_unsigned(4, 8) ) ELSE
                     delay_pipeline(5) WHEN ( cur_count = to_unsigned(5, 8) ) ELSE
                     delay_pipeline(6) WHEN ( cur_count = to_unsigned(6, 8) ) ELSE
                     delay_pipeline(7) WHEN ( cur_count = to_unsigned(7, 8) ) ELSE
                     delay_pipeline(8) WHEN ( cur_count = to_unsigned(8, 8) ) ELSE
                     delay_pipeline(9) WHEN ( cur_count = to_unsigned(9, 8) ) ELSE
                     delay_pipeline(10) WHEN ( cur_count = to_unsigned(10, 8) ) ELSE
                     delay_pipeline(11) WHEN ( cur_count = to_unsigned(11, 8) ) ELSE
                     delay_pipeline(12) WHEN ( cur_count = to_unsigned(12, 8) ) ELSE
                     delay_pipeline(13) WHEN ( cur_count = to_unsigned(13, 8) ) ELSE
                     delay_pipeline(14) WHEN ( cur_count = to_unsigned(14, 8) ) ELSE
                     delay_pipeline(15) WHEN ( cur_count = to_unsigned(15, 8) ) ELSE
                     delay_pipeline(16) WHEN ( cur_count = to_unsigned(16, 8) ) ELSE
                     delay_pipeline(17) WHEN ( cur_count = to_unsigned(17, 8) ) ELSE
                     delay_pipeline(18) WHEN ( cur_count = to_unsigned(18, 8) ) ELSE
                     delay_pipeline(19) WHEN ( cur_count = to_unsigned(19, 8) ) ELSE
                     delay_pipeline(20) WHEN ( cur_count = to_unsigned(20, 8) ) ELSE
                     delay_pipeline(21) WHEN ( cur_count = to_unsigned(21, 8) ) ELSE
                     delay_pipeline(22) WHEN ( cur_count = to_unsigned(22, 8) ) ELSE
                     delay_pipeline(23) WHEN ( cur_count = to_unsigned(23, 8) ) ELSE
                     delay_pipeline(24) WHEN ( cur_count = to_unsigned(24, 8) ) ELSE
                     delay_pipeline(25) WHEN ( cur_count = to_unsigned(25, 8) ) ELSE
                     delay_pipeline(26) WHEN ( cur_count = to_unsigned(26, 8) ) ELSE
                     delay_pipeline(27) WHEN ( cur_count = to_unsigned(27, 8) ) ELSE
                     delay_pipeline(28) WHEN ( cur_count = to_unsigned(28, 8) ) ELSE
                     delay_pipeline(29) WHEN ( cur_count = to_unsigned(29, 8) ) ELSE
                     delay_pipeline(30) WHEN ( cur_count = to_unsigned(30, 8) ) ELSE
                     delay_pipeline(31) WHEN ( cur_count = to_unsigned(31, 8) ) ELSE
                     delay_pipeline(32) WHEN ( cur_count = to_unsigned(32, 8) ) ELSE
                     delay_pipeline(33) WHEN ( cur_count = to_unsigned(33, 8) ) ELSE
                     delay_pipeline(34) WHEN ( cur_count = to_unsigned(34, 8) ) ELSE
                     delay_pipeline(35) WHEN ( cur_count = to_unsigned(35, 8) ) ELSE
                     delay_pipeline(36) WHEN ( cur_count = to_unsigned(36, 8) ) ELSE
                     delay_pipeline(37) WHEN ( cur_count = to_unsigned(37, 8) ) ELSE
                     delay_pipeline(38) WHEN ( cur_count = to_unsigned(38, 8) ) ELSE
                     delay_pipeline(39) WHEN ( cur_count = to_unsigned(39, 8) ) ELSE
                     delay_pipeline(40) WHEN ( cur_count = to_unsigned(40, 8) ) ELSE
                     delay_pipeline(41) WHEN ( cur_count = to_unsigned(41, 8) ) ELSE
                     delay_pipeline(42) WHEN ( cur_count = to_unsigned(42, 8) ) ELSE
                     delay_pipeline(43) WHEN ( cur_count = to_unsigned(43, 8) ) ELSE
                     delay_pipeline(44) WHEN ( cur_count = to_unsigned(44, 8) ) ELSE
                     delay_pipeline(45) WHEN ( cur_count = to_unsigned(45, 8) ) ELSE
                     delay_pipeline(46) WHEN ( cur_count = to_unsigned(46, 8) ) ELSE
                     delay_pipeline(47) WHEN ( cur_count = to_unsigned(47, 8) ) ELSE
                     delay_pipeline(48) WHEN ( cur_count = to_unsigned(48, 8) ) ELSE
                     delay_pipeline(49) WHEN ( cur_count = to_unsigned(49, 8) ) ELSE
                     delay_pipeline(50) WHEN ( cur_count = to_unsigned(50, 8) ) ELSE
                     delay_pipeline(51) WHEN ( cur_count = to_unsigned(51, 8) ) ELSE
                     delay_pipeline(52) WHEN ( cur_count = to_unsigned(52, 8) ) ELSE
                     delay_pipeline(53) WHEN ( cur_count = to_unsigned(53, 8) ) ELSE
                     delay_pipeline(54) WHEN ( cur_count = to_unsigned(54, 8) ) ELSE
                     delay_pipeline(55) WHEN ( cur_count = to_unsigned(55, 8) ) ELSE
                     delay_pipeline(56) WHEN ( cur_count = to_unsigned(56, 8) ) ELSE
                     delay_pipeline(57) WHEN ( cur_count = to_unsigned(57, 8) ) ELSE
                     delay_pipeline(58) WHEN ( cur_count = to_unsigned(58, 8) ) ELSE
                     delay_pipeline(59) WHEN ( cur_count = to_unsigned(59, 8) ) ELSE
                     delay_pipeline(60) WHEN ( cur_count = to_unsigned(60, 8) ) ELSE
                     delay_pipeline(61) WHEN ( cur_count = to_unsigned(61, 8) ) ELSE
                     delay_pipeline(62) WHEN ( cur_count = to_unsigned(62, 8) ) ELSE
                     delay_pipeline(63) WHEN ( cur_count = to_unsigned(63, 8) ) ELSE
                     delay_pipeline(64) WHEN ( cur_count = to_unsigned(64, 8) ) ELSE
                     delay_pipeline(65) WHEN ( cur_count = to_unsigned(65, 8) ) ELSE
                     delay_pipeline(66) WHEN ( cur_count = to_unsigned(66, 8) ) ELSE
                     delay_pipeline(67) WHEN ( cur_count = to_unsigned(67, 8) ) ELSE
                     delay_pipeline(68) WHEN ( cur_count = to_unsigned(68, 8) ) ELSE
                     delay_pipeline(69) WHEN ( cur_count = to_unsigned(69, 8) ) ELSE
                     delay_pipeline(70) WHEN ( cur_count = to_unsigned(70, 8) ) ELSE
                     delay_pipeline(71) WHEN ( cur_count = to_unsigned(71, 8) ) ELSE
                     delay_pipeline(72) WHEN ( cur_count = to_unsigned(72, 8) ) ELSE
                     delay_pipeline(73) WHEN ( cur_count = to_unsigned(73, 8) ) ELSE
                     delay_pipeline(74) WHEN ( cur_count = to_unsigned(74, 8) ) ELSE
                     delay_pipeline(75) WHEN ( cur_count = to_unsigned(75, 8) ) ELSE
                     delay_pipeline(76) WHEN ( cur_count = to_unsigned(76, 8) ) ELSE
                     delay_pipeline(77) WHEN ( cur_count = to_unsigned(77, 8) ) ELSE
                     delay_pipeline(78) WHEN ( cur_count = to_unsigned(78, 8) ) ELSE
                     delay_pipeline(79) WHEN ( cur_count = to_unsigned(79, 8) ) ELSE
                     delay_pipeline(80) WHEN ( cur_count = to_unsigned(80, 8) ) ELSE
                     delay_pipeline(81) WHEN ( cur_count = to_unsigned(81, 8) ) ELSE
                     delay_pipeline(82) WHEN ( cur_count = to_unsigned(82, 8) ) ELSE
                     delay_pipeline(83) WHEN ( cur_count = to_unsigned(83, 8) ) ELSE
                     delay_pipeline(84) WHEN ( cur_count = to_unsigned(84, 8) ) ELSE
                     delay_pipeline(85) WHEN ( cur_count = to_unsigned(85, 8) ) ELSE
                     delay_pipeline(86) WHEN ( cur_count = to_unsigned(86, 8) ) ELSE
                     delay_pipeline(87) WHEN ( cur_count = to_unsigned(87, 8) ) ELSE
                     delay_pipeline(88) WHEN ( cur_count = to_unsigned(88, 8) ) ELSE
                     delay_pipeline(89) WHEN ( cur_count = to_unsigned(89, 8) ) ELSE
                     delay_pipeline(90) WHEN ( cur_count = to_unsigned(90, 8) ) ELSE
                     delay_pipeline(91) WHEN ( cur_count = to_unsigned(91, 8) ) ELSE
                     delay_pipeline(92) WHEN ( cur_count = to_unsigned(92, 8) ) ELSE
                     delay_pipeline(93) WHEN ( cur_count = to_unsigned(93, 8) ) ELSE
                     delay_pipeline(94) WHEN ( cur_count = to_unsigned(94, 8) ) ELSE
                     delay_pipeline(95) WHEN ( cur_count = to_unsigned(95, 8) ) ELSE
                     delay_pipeline(96) WHEN ( cur_count = to_unsigned(96, 8) ) ELSE
                     delay_pipeline(97) WHEN ( cur_count = to_unsigned(97, 8) ) ELSE
                     delay_pipeline(98) WHEN ( cur_count = to_unsigned(98, 8) ) ELSE
                     delay_pipeline(99) WHEN ( cur_count = to_unsigned(99, 8) ) ELSE
                     delay_pipeline(100) WHEN ( cur_count = to_unsigned(100, 8) ) ELSE
                     delay_pipeline(101) WHEN ( cur_count = to_unsigned(101, 8) ) ELSE
                     delay_pipeline(102) WHEN ( cur_count = to_unsigned(102, 8) ) ELSE
                     delay_pipeline(103) WHEN ( cur_count = to_unsigned(103, 8) ) ELSE
                     delay_pipeline(104) WHEN ( cur_count = to_unsigned(104, 8) ) ELSE
                     delay_pipeline(105) WHEN ( cur_count = to_unsigned(105, 8) ) ELSE
                     delay_pipeline(106) WHEN ( cur_count = to_unsigned(106, 8) ) ELSE
                     delay_pipeline(107) WHEN ( cur_count = to_unsigned(107, 8) ) ELSE
                     delay_pipeline(108) WHEN ( cur_count = to_unsigned(108, 8) ) ELSE
                     delay_pipeline(109) WHEN ( cur_count = to_unsigned(109, 8) ) ELSE
                     delay_pipeline(110) WHEN ( cur_count = to_unsigned(110, 8) ) ELSE
                     delay_pipeline(111) WHEN ( cur_count = to_unsigned(111, 8) ) ELSE
                     delay_pipeline(112) WHEN ( cur_count = to_unsigned(112, 8) ) ELSE
                     delay_pipeline(113) WHEN ( cur_count = to_unsigned(113, 8) ) ELSE
                     delay_pipeline(114) WHEN ( cur_count = to_unsigned(114, 8) ) ELSE
                     delay_pipeline(115) WHEN ( cur_count = to_unsigned(115, 8) ) ELSE
                     delay_pipeline(116) WHEN ( cur_count = to_unsigned(116, 8) ) ELSE
                     delay_pipeline(117) WHEN ( cur_count = to_unsigned(117, 8) ) ELSE
                     delay_pipeline(118) WHEN ( cur_count = to_unsigned(118, 8) ) ELSE
                     delay_pipeline(119) WHEN ( cur_count = to_unsigned(119, 8) ) ELSE
                     delay_pipeline(120) WHEN ( cur_count = to_unsigned(120, 8) ) ELSE
                     delay_pipeline(121) WHEN ( cur_count = to_unsigned(121, 8) ) ELSE
                     delay_pipeline(122) WHEN ( cur_count = to_unsigned(122, 8) ) ELSE
                     delay_pipeline(123) WHEN ( cur_count = to_unsigned(123, 8) ) ELSE
                     delay_pipeline(124) WHEN ( cur_count = to_unsigned(124, 8) ) ELSE
                     delay_pipeline(125) WHEN ( cur_count = to_unsigned(125, 8) ) ELSE
                     delay_pipeline(126) WHEN ( cur_count = to_unsigned(126, 8) ) ELSE
                     delay_pipeline(127) WHEN ( cur_count = to_unsigned(127, 8) ) ELSE
                     delay_pipeline(128) WHEN ( cur_count = to_unsigned(128, 8) ) ELSE
                     delay_pipeline(129) WHEN ( cur_count = to_unsigned(129, 8) ) ELSE
                     delay_pipeline(130) WHEN ( cur_count = to_unsigned(130, 8) ) ELSE
                     delay_pipeline(131) WHEN ( cur_count = to_unsigned(131, 8) ) ELSE
                     delay_pipeline(132) WHEN ( cur_count = to_unsigned(132, 8) ) ELSE
                     delay_pipeline(133) WHEN ( cur_count = to_unsigned(133, 8) ) ELSE
                     delay_pipeline(134) WHEN ( cur_count = to_unsigned(134, 8) ) ELSE
                     delay_pipeline(135) WHEN ( cur_count = to_unsigned(135, 8) ) ELSE
                     delay_pipeline(136) WHEN ( cur_count = to_unsigned(136, 8) ) ELSE
                     delay_pipeline(137) WHEN ( cur_count = to_unsigned(137, 8) ) ELSE
                     delay_pipeline(138) WHEN ( cur_count = to_unsigned(138, 8) ) ELSE
                     delay_pipeline(139) WHEN ( cur_count = to_unsigned(139, 8) ) ELSE
                     delay_pipeline(140) WHEN ( cur_count = to_unsigned(140, 8) ) ELSE
                     delay_pipeline(141) WHEN ( cur_count = to_unsigned(141, 8) ) ELSE
                     delay_pipeline(142) WHEN ( cur_count = to_unsigned(142, 8) ) ELSE
                     delay_pipeline(143) WHEN ( cur_count = to_unsigned(143, 8) ) ELSE
                     delay_pipeline(144) WHEN ( cur_count = to_unsigned(144, 8) ) ELSE
                     delay_pipeline(145) WHEN ( cur_count = to_unsigned(145, 8) ) ELSE
                     delay_pipeline(146) WHEN ( cur_count = to_unsigned(146, 8) ) ELSE
                     delay_pipeline(147) WHEN ( cur_count = to_unsigned(147, 8) ) ELSE
                     delay_pipeline(148) WHEN ( cur_count = to_unsigned(148, 8) ) ELSE
                     delay_pipeline(149) WHEN ( cur_count = to_unsigned(149, 8) ) ELSE
                     delay_pipeline(150) WHEN ( cur_count = to_unsigned(150, 8) ) ELSE
                     delay_pipeline(151) WHEN ( cur_count = to_unsigned(151, 8) ) ELSE
                     delay_pipeline(152) WHEN ( cur_count = to_unsigned(152, 8) ) ELSE
                     delay_pipeline(153) WHEN ( cur_count = to_unsigned(153, 8) ) ELSE
                     delay_pipeline(154) WHEN ( cur_count = to_unsigned(154, 8) ) ELSE
                     delay_pipeline(155) WHEN ( cur_count = to_unsigned(155, 8) ) ELSE
                     delay_pipeline(156) WHEN ( cur_count = to_unsigned(156, 8) ) ELSE
                     delay_pipeline(157) WHEN ( cur_count = to_unsigned(157, 8) ) ELSE
                     delay_pipeline(158) WHEN ( cur_count = to_unsigned(158, 8) ) ELSE
                     delay_pipeline(159) WHEN ( cur_count = to_unsigned(159, 8) ) ELSE
                     delay_pipeline(160) WHEN ( cur_count = to_unsigned(160, 8) ) ELSE
                     delay_pipeline(161) WHEN ( cur_count = to_unsigned(161, 8) ) ELSE
                     delay_pipeline(162) WHEN ( cur_count = to_unsigned(162, 8) ) ELSE
                     delay_pipeline(163) WHEN ( cur_count = to_unsigned(163, 8) ) ELSE
                     delay_pipeline(164) WHEN ( cur_count = to_unsigned(164, 8) ) ELSE
                     delay_pipeline(165) WHEN ( cur_count = to_unsigned(165, 8) ) ELSE
                     delay_pipeline(166) WHEN ( cur_count = to_unsigned(166, 8) ) ELSE
                     delay_pipeline(167) WHEN ( cur_count = to_unsigned(167, 8) ) ELSE
                     delay_pipeline(168) WHEN ( cur_count = to_unsigned(168, 8) ) ELSE
                     delay_pipeline(169) WHEN ( cur_count = to_unsigned(169, 8) ) ELSE
                     delay_pipeline(170) WHEN ( cur_count = to_unsigned(170, 8) ) ELSE
                     delay_pipeline(171) WHEN ( cur_count = to_unsigned(171, 8) ) ELSE
                     delay_pipeline(172) WHEN ( cur_count = to_unsigned(172, 8) ) ELSE
                     delay_pipeline(173) WHEN ( cur_count = to_unsigned(173, 8) ) ELSE
                     delay_pipeline(174) WHEN ( cur_count = to_unsigned(174, 8) ) ELSE
                     delay_pipeline(175) WHEN ( cur_count = to_unsigned(175, 8) ) ELSE
                     delay_pipeline(176) WHEN ( cur_count = to_unsigned(176, 8) ) ELSE
                     delay_pipeline(177) WHEN ( cur_count = to_unsigned(177, 8) ) ELSE
                     delay_pipeline(178) WHEN ( cur_count = to_unsigned(178, 8) ) ELSE
                     delay_pipeline(179) WHEN ( cur_count = to_unsigned(179, 8) ) ELSE
                     delay_pipeline(180) WHEN ( cur_count = to_unsigned(180, 8) ) ELSE
                     delay_pipeline(181) WHEN ( cur_count = to_unsigned(181, 8) ) ELSE
                     delay_pipeline(182) WHEN ( cur_count = to_unsigned(182, 8) ) ELSE
                     delay_pipeline(183) WHEN ( cur_count = to_unsigned(183, 8) ) ELSE
                     delay_pipeline(184) WHEN ( cur_count = to_unsigned(184, 8) ) ELSE
                     delay_pipeline(185) WHEN ( cur_count = to_unsigned(185, 8) ) ELSE
                     delay_pipeline(186) WHEN ( cur_count = to_unsigned(186, 8) ) ELSE
                     delay_pipeline(187) WHEN ( cur_count = to_unsigned(187, 8) ) ELSE
                     delay_pipeline(188) WHEN ( cur_count = to_unsigned(188, 8) ) ELSE
                     delay_pipeline(189) WHEN ( cur_count = to_unsigned(189, 8) ) ELSE
                     delay_pipeline(190) WHEN ( cur_count = to_unsigned(190, 8) ) ELSE
                     delay_pipeline(191) WHEN ( cur_count = to_unsigned(191, 8) ) ELSE
                     delay_pipeline(192) WHEN ( cur_count = to_unsigned(192, 8) ) ELSE
                     delay_pipeline(193) WHEN ( cur_count = to_unsigned(193, 8) ) ELSE
                     delay_pipeline(194) WHEN ( cur_count = to_unsigned(194, 8) ) ELSE
                     delay_pipeline(195) WHEN ( cur_count = to_unsigned(195, 8) ) ELSE
                     delay_pipeline(196) WHEN ( cur_count = to_unsigned(196, 8) ) ELSE
                     delay_pipeline(197) WHEN ( cur_count = to_unsigned(197, 8) ) ELSE
                     delay_pipeline(198) WHEN ( cur_count = to_unsigned(198, 8) ) ELSE
                     delay_pipeline(199) WHEN ( cur_count = to_unsigned(199, 8) ) ELSE
                     delay_pipeline(200) WHEN ( cur_count = to_unsigned(200, 8) ) ELSE
                     delay_pipeline(201) WHEN ( cur_count = to_unsigned(201, 8) ) ELSE
                     delay_pipeline(202) WHEN ( cur_count = to_unsigned(202, 8) ) ELSE
                     delay_pipeline(203) WHEN ( cur_count = to_unsigned(203, 8) ) ELSE
                     delay_pipeline(204) WHEN ( cur_count = to_unsigned(204, 8) ) ELSE
                     delay_pipeline(205) WHEN ( cur_count = to_unsigned(205, 8) ) ELSE
                     delay_pipeline(206) WHEN ( cur_count = to_unsigned(206, 8) ) ELSE
                     delay_pipeline(207) WHEN ( cur_count = to_unsigned(207, 8) ) ELSE
                     delay_pipeline(208) WHEN ( cur_count = to_unsigned(208, 8) ) ELSE
                     delay_pipeline(209) WHEN ( cur_count = to_unsigned(209, 8) ) ELSE
                     delay_pipeline(210) WHEN ( cur_count = to_unsigned(210, 8) ) ELSE
                     delay_pipeline(211) WHEN ( cur_count = to_unsigned(211, 8) ) ELSE
                     delay_pipeline(212) WHEN ( cur_count = to_unsigned(212, 8) ) ELSE
                     delay_pipeline(213) WHEN ( cur_count = to_unsigned(213, 8) ) ELSE
                     delay_pipeline(214) WHEN ( cur_count = to_unsigned(214, 8) ) ELSE
                     delay_pipeline(215) WHEN ( cur_count = to_unsigned(215, 8) ) ELSE
                     delay_pipeline(216) WHEN ( cur_count = to_unsigned(216, 8) ) ELSE
                     delay_pipeline(217) WHEN ( cur_count = to_unsigned(217, 8) ) ELSE
                     delay_pipeline(218) WHEN ( cur_count = to_unsigned(218, 8) ) ELSE
                     delay_pipeline(219) WHEN ( cur_count = to_unsigned(219, 8) ) ELSE
                     delay_pipeline(220) WHEN ( cur_count = to_unsigned(220, 8) ) ELSE
                     delay_pipeline(221) WHEN ( cur_count = to_unsigned(221, 8) ) ELSE
                     delay_pipeline(222) WHEN ( cur_count = to_unsigned(222, 8) ) ELSE
                     delay_pipeline(223) WHEN ( cur_count = to_unsigned(223, 8) ) ELSE
                     delay_pipeline(224) WHEN ( cur_count = to_unsigned(224, 8) ) ELSE
                     delay_pipeline(225) WHEN ( cur_count = to_unsigned(225, 8) ) ELSE
                     delay_pipeline(226) WHEN ( cur_count = to_unsigned(226, 8) ) ELSE
                     delay_pipeline(227) WHEN ( cur_count = to_unsigned(227, 8) ) ELSE
                     delay_pipeline(228) WHEN ( cur_count = to_unsigned(228, 8) ) ELSE
                     delay_pipeline(229) WHEN ( cur_count = to_unsigned(229, 8) ) ELSE
                     delay_pipeline(230) WHEN ( cur_count = to_unsigned(230, 8) ) ELSE
                     delay_pipeline(231) WHEN ( cur_count = to_unsigned(231, 8) ) ELSE
                     delay_pipeline(232) WHEN ( cur_count = to_unsigned(232, 8) ) ELSE
                     delay_pipeline(233) WHEN ( cur_count = to_unsigned(233, 8) ) ELSE
                     delay_pipeline(234) WHEN ( cur_count = to_unsigned(234, 8) ) ELSE
                     delay_pipeline(235) WHEN ( cur_count = to_unsigned(235, 8) ) ELSE
                     delay_pipeline(236) WHEN ( cur_count = to_unsigned(236, 8) ) ELSE
                     delay_pipeline(237) WHEN ( cur_count = to_unsigned(237, 8) ) ELSE
                     delay_pipeline(238) WHEN ( cur_count = to_unsigned(238, 8) ) ELSE
                     delay_pipeline(239) WHEN ( cur_count = to_unsigned(239, 8) ) ELSE
                     delay_pipeline(240) WHEN ( cur_count = to_unsigned(240, 8) ) ELSE
                     delay_pipeline(241) WHEN ( cur_count = to_unsigned(241, 8) ) ELSE
                     delay_pipeline(242) WHEN ( cur_count = to_unsigned(242, 8) ) ELSE
                     delay_pipeline(243) WHEN ( cur_count = to_unsigned(243, 8) ) ELSE
                     delay_pipeline(244) WHEN ( cur_count = to_unsigned(244, 8) ) ELSE
                     delay_pipeline(245) WHEN ( cur_count = to_unsigned(245, 8) ) ELSE
                     delay_pipeline(246) WHEN ( cur_count = to_unsigned(246, 8) ) ELSE
                     delay_pipeline(247) WHEN ( cur_count = to_unsigned(247, 8) ) ELSE
                     delay_pipeline(248) WHEN ( cur_count = to_unsigned(248, 8) ) ELSE
                     delay_pipeline(249) WHEN ( cur_count = to_unsigned(249, 8) ) ELSE
                     delay_pipeline(250) WHEN ( cur_count = to_unsigned(250, 8) ) ELSE
                     delay_pipeline(251) WHEN ( cur_count = to_unsigned(251, 8) ) ELSE
                     delay_pipeline(252) WHEN ( cur_count = to_unsigned(252, 8) ) ELSE
                     delay_pipeline(253) WHEN ( cur_count = to_unsigned(253, 8) ) ELSE
                     delay_pipeline(254) WHEN ( cur_count = to_unsigned(254, 8) ) ELSE
                     delay_pipeline(255);

  --   ------------------ Serial partition # 1 ------------------

  product_1_mux <= coeff1 WHEN ( cur_count = to_unsigned(0, 8) ) ELSE
                        coeff2 WHEN ( cur_count = to_unsigned(1, 8) ) ELSE
                        coeff3 WHEN ( cur_count = to_unsigned(2, 8) ) ELSE
                        coeff4 WHEN ( cur_count = to_unsigned(3, 8) ) ELSE
                        coeff5 WHEN ( cur_count = to_unsigned(4, 8) ) ELSE
                        coeff6 WHEN ( cur_count = to_unsigned(5, 8) ) ELSE
                        coeff7 WHEN ( cur_count = to_unsigned(6, 8) ) ELSE
                        coeff8 WHEN ( cur_count = to_unsigned(7, 8) ) ELSE
                        coeff9 WHEN ( cur_count = to_unsigned(8, 8) ) ELSE
                        coeff10 WHEN ( cur_count = to_unsigned(9, 8) ) ELSE
                        coeff11 WHEN ( cur_count = to_unsigned(10, 8) ) ELSE
                        coeff12 WHEN ( cur_count = to_unsigned(11, 8) ) ELSE
                        coeff13 WHEN ( cur_count = to_unsigned(12, 8) ) ELSE
                        coeff14 WHEN ( cur_count = to_unsigned(13, 8) ) ELSE
                        coeff15 WHEN ( cur_count = to_unsigned(14, 8) ) ELSE
                        coeff16 WHEN ( cur_count = to_unsigned(15, 8) ) ELSE
                        coeff17 WHEN ( cur_count = to_unsigned(16, 8) ) ELSE
                        coeff18 WHEN ( cur_count = to_unsigned(17, 8) ) ELSE
                        coeff19 WHEN ( cur_count = to_unsigned(18, 8) ) ELSE
                        coeff20 WHEN ( cur_count = to_unsigned(19, 8) ) ELSE
                        coeff21 WHEN ( cur_count = to_unsigned(20, 8) ) ELSE
                        coeff22 WHEN ( cur_count = to_unsigned(21, 8) ) ELSE
                        coeff23 WHEN ( cur_count = to_unsigned(22, 8) ) ELSE
                        coeff24 WHEN ( cur_count = to_unsigned(23, 8) ) ELSE
                        coeff25 WHEN ( cur_count = to_unsigned(24, 8) ) ELSE
                        coeff26 WHEN ( cur_count = to_unsigned(25, 8) ) ELSE
                        coeff27 WHEN ( cur_count = to_unsigned(26, 8) ) ELSE
                        coeff28 WHEN ( cur_count = to_unsigned(27, 8) ) ELSE
                        coeff29 WHEN ( cur_count = to_unsigned(28, 8) ) ELSE
                        coeff30 WHEN ( cur_count = to_unsigned(29, 8) ) ELSE
                        coeff31 WHEN ( cur_count = to_unsigned(30, 8) ) ELSE
                        coeff32 WHEN ( cur_count = to_unsigned(31, 8) ) ELSE
                        coeff33 WHEN ( cur_count = to_unsigned(32, 8) ) ELSE
                        coeff34 WHEN ( cur_count = to_unsigned(33, 8) ) ELSE
                        coeff35 WHEN ( cur_count = to_unsigned(34, 8) ) ELSE
                        coeff36 WHEN ( cur_count = to_unsigned(35, 8) ) ELSE
                        coeff37 WHEN ( cur_count = to_unsigned(36, 8) ) ELSE
                        coeff38 WHEN ( cur_count = to_unsigned(37, 8) ) ELSE
                        coeff39 WHEN ( cur_count = to_unsigned(38, 8) ) ELSE
                        coeff40 WHEN ( cur_count = to_unsigned(39, 8) ) ELSE
                        coeff41 WHEN ( cur_count = to_unsigned(40, 8) ) ELSE
                        coeff42 WHEN ( cur_count = to_unsigned(41, 8) ) ELSE
                        coeff43 WHEN ( cur_count = to_unsigned(42, 8) ) ELSE
                        coeff44 WHEN ( cur_count = to_unsigned(43, 8) ) ELSE
                        coeff45 WHEN ( cur_count = to_unsigned(44, 8) ) ELSE
                        coeff46 WHEN ( cur_count = to_unsigned(45, 8) ) ELSE
                        coeff47 WHEN ( cur_count = to_unsigned(46, 8) ) ELSE
                        coeff48 WHEN ( cur_count = to_unsigned(47, 8) ) ELSE
                        coeff49 WHEN ( cur_count = to_unsigned(48, 8) ) ELSE
                        coeff50 WHEN ( cur_count = to_unsigned(49, 8) ) ELSE
                        coeff51 WHEN ( cur_count = to_unsigned(50, 8) ) ELSE
                        coeff52 WHEN ( cur_count = to_unsigned(51, 8) ) ELSE
                        coeff53 WHEN ( cur_count = to_unsigned(52, 8) ) ELSE
                        coeff54 WHEN ( cur_count = to_unsigned(53, 8) ) ELSE
                        coeff55 WHEN ( cur_count = to_unsigned(54, 8) ) ELSE
                        coeff56 WHEN ( cur_count = to_unsigned(55, 8) ) ELSE
                        coeff57 WHEN ( cur_count = to_unsigned(56, 8) ) ELSE
                        coeff58 WHEN ( cur_count = to_unsigned(57, 8) ) ELSE
                        coeff59 WHEN ( cur_count = to_unsigned(58, 8) ) ELSE
                        coeff60 WHEN ( cur_count = to_unsigned(59, 8) ) ELSE
                        coeff61 WHEN ( cur_count = to_unsigned(60, 8) ) ELSE
                        coeff62 WHEN ( cur_count = to_unsigned(61, 8) ) ELSE
                        coeff63 WHEN ( cur_count = to_unsigned(62, 8) ) ELSE
                        coeff64 WHEN ( cur_count = to_unsigned(63, 8) ) ELSE
                        coeff65 WHEN ( cur_count = to_unsigned(64, 8) ) ELSE
                        coeff66 WHEN ( cur_count = to_unsigned(65, 8) ) ELSE
                        coeff67 WHEN ( cur_count = to_unsigned(66, 8) ) ELSE
                        coeff68 WHEN ( cur_count = to_unsigned(67, 8) ) ELSE
                        coeff69 WHEN ( cur_count = to_unsigned(68, 8) ) ELSE
                        coeff70 WHEN ( cur_count = to_unsigned(69, 8) ) ELSE
                        coeff71 WHEN ( cur_count = to_unsigned(70, 8) ) ELSE
                        coeff72 WHEN ( cur_count = to_unsigned(71, 8) ) ELSE
                        coeff73 WHEN ( cur_count = to_unsigned(72, 8) ) ELSE
                        coeff74 WHEN ( cur_count = to_unsigned(73, 8) ) ELSE
                        coeff75 WHEN ( cur_count = to_unsigned(74, 8) ) ELSE
                        coeff76 WHEN ( cur_count = to_unsigned(75, 8) ) ELSE
                        coeff77 WHEN ( cur_count = to_unsigned(76, 8) ) ELSE
                        coeff78 WHEN ( cur_count = to_unsigned(77, 8) ) ELSE
                        coeff79 WHEN ( cur_count = to_unsigned(78, 8) ) ELSE
                        coeff80 WHEN ( cur_count = to_unsigned(79, 8) ) ELSE
                        coeff81 WHEN ( cur_count = to_unsigned(80, 8) ) ELSE
                        coeff82 WHEN ( cur_count = to_unsigned(81, 8) ) ELSE
                        coeff83 WHEN ( cur_count = to_unsigned(82, 8) ) ELSE
                        coeff84 WHEN ( cur_count = to_unsigned(83, 8) ) ELSE
                        coeff85 WHEN ( cur_count = to_unsigned(84, 8) ) ELSE
                        coeff86 WHEN ( cur_count = to_unsigned(85, 8) ) ELSE
                        coeff87 WHEN ( cur_count = to_unsigned(86, 8) ) ELSE
                        coeff88 WHEN ( cur_count = to_unsigned(87, 8) ) ELSE
                        coeff89 WHEN ( cur_count = to_unsigned(88, 8) ) ELSE
                        coeff90 WHEN ( cur_count = to_unsigned(89, 8) ) ELSE
                        coeff91 WHEN ( cur_count = to_unsigned(90, 8) ) ELSE
                        coeff92 WHEN ( cur_count = to_unsigned(91, 8) ) ELSE
                        coeff93 WHEN ( cur_count = to_unsigned(92, 8) ) ELSE
                        coeff94 WHEN ( cur_count = to_unsigned(93, 8) ) ELSE
                        coeff95 WHEN ( cur_count = to_unsigned(94, 8) ) ELSE
                        coeff96 WHEN ( cur_count = to_unsigned(95, 8) ) ELSE
                        coeff97 WHEN ( cur_count = to_unsigned(96, 8) ) ELSE
                        coeff98 WHEN ( cur_count = to_unsigned(97, 8) ) ELSE
                        coeff99 WHEN ( cur_count = to_unsigned(98, 8) ) ELSE
                        coeff100 WHEN ( cur_count = to_unsigned(99, 8) ) ELSE
                        coeff101 WHEN ( cur_count = to_unsigned(100, 8) ) ELSE
                        coeff102 WHEN ( cur_count = to_unsigned(101, 8) ) ELSE
                        coeff103 WHEN ( cur_count = to_unsigned(102, 8) ) ELSE
                        coeff104 WHEN ( cur_count = to_unsigned(103, 8) ) ELSE
                        coeff105 WHEN ( cur_count = to_unsigned(104, 8) ) ELSE
                        coeff106 WHEN ( cur_count = to_unsigned(105, 8) ) ELSE
                        coeff107 WHEN ( cur_count = to_unsigned(106, 8) ) ELSE
                        coeff108 WHEN ( cur_count = to_unsigned(107, 8) ) ELSE
                        coeff109 WHEN ( cur_count = to_unsigned(108, 8) ) ELSE
                        coeff110 WHEN ( cur_count = to_unsigned(109, 8) ) ELSE
                        coeff111 WHEN ( cur_count = to_unsigned(110, 8) ) ELSE
                        coeff112 WHEN ( cur_count = to_unsigned(111, 8) ) ELSE
                        coeff113 WHEN ( cur_count = to_unsigned(112, 8) ) ELSE
                        coeff114 WHEN ( cur_count = to_unsigned(113, 8) ) ELSE
                        coeff115 WHEN ( cur_count = to_unsigned(114, 8) ) ELSE
                        coeff116 WHEN ( cur_count = to_unsigned(115, 8) ) ELSE
                        coeff117 WHEN ( cur_count = to_unsigned(116, 8) ) ELSE
                        coeff118 WHEN ( cur_count = to_unsigned(117, 8) ) ELSE
                        coeff119 WHEN ( cur_count = to_unsigned(118, 8) ) ELSE
                        coeff120 WHEN ( cur_count = to_unsigned(119, 8) ) ELSE
                        coeff121 WHEN ( cur_count = to_unsigned(120, 8) ) ELSE
                        coeff122 WHEN ( cur_count = to_unsigned(121, 8) ) ELSE
                        coeff123 WHEN ( cur_count = to_unsigned(122, 8) ) ELSE
                        coeff124 WHEN ( cur_count = to_unsigned(123, 8) ) ELSE
                        coeff125 WHEN ( cur_count = to_unsigned(124, 8) ) ELSE
                        coeff126 WHEN ( cur_count = to_unsigned(125, 8) ) ELSE
                        coeff127 WHEN ( cur_count = to_unsigned(126, 8) ) ELSE
                        coeff128 WHEN ( cur_count = to_unsigned(127, 8) ) ELSE
                        coeff129 WHEN ( cur_count = to_unsigned(128, 8) ) ELSE
                        coeff130 WHEN ( cur_count = to_unsigned(129, 8) ) ELSE
                        coeff131 WHEN ( cur_count = to_unsigned(130, 8) ) ELSE
                        coeff132 WHEN ( cur_count = to_unsigned(131, 8) ) ELSE
                        coeff133 WHEN ( cur_count = to_unsigned(132, 8) ) ELSE
                        coeff134 WHEN ( cur_count = to_unsigned(133, 8) ) ELSE
                        coeff135 WHEN ( cur_count = to_unsigned(134, 8) ) ELSE
                        coeff136 WHEN ( cur_count = to_unsigned(135, 8) ) ELSE
                        coeff137 WHEN ( cur_count = to_unsigned(136, 8) ) ELSE
                        coeff138 WHEN ( cur_count = to_unsigned(137, 8) ) ELSE
                        coeff139 WHEN ( cur_count = to_unsigned(138, 8) ) ELSE
                        coeff140 WHEN ( cur_count = to_unsigned(139, 8) ) ELSE
                        coeff141 WHEN ( cur_count = to_unsigned(140, 8) ) ELSE
                        coeff142 WHEN ( cur_count = to_unsigned(141, 8) ) ELSE
                        coeff143 WHEN ( cur_count = to_unsigned(142, 8) ) ELSE
                        coeff144 WHEN ( cur_count = to_unsigned(143, 8) ) ELSE
                        coeff145 WHEN ( cur_count = to_unsigned(144, 8) ) ELSE
                        coeff146 WHEN ( cur_count = to_unsigned(145, 8) ) ELSE
                        coeff147 WHEN ( cur_count = to_unsigned(146, 8) ) ELSE
                        coeff148 WHEN ( cur_count = to_unsigned(147, 8) ) ELSE
                        coeff149 WHEN ( cur_count = to_unsigned(148, 8) ) ELSE
                        coeff150 WHEN ( cur_count = to_unsigned(149, 8) ) ELSE
                        coeff151 WHEN ( cur_count = to_unsigned(150, 8) ) ELSE
                        coeff152 WHEN ( cur_count = to_unsigned(151, 8) ) ELSE
                        coeff153 WHEN ( cur_count = to_unsigned(152, 8) ) ELSE
                        coeff154 WHEN ( cur_count = to_unsigned(153, 8) ) ELSE
                        coeff155 WHEN ( cur_count = to_unsigned(154, 8) ) ELSE
                        coeff156 WHEN ( cur_count = to_unsigned(155, 8) ) ELSE
                        coeff157 WHEN ( cur_count = to_unsigned(156, 8) ) ELSE
                        coeff158 WHEN ( cur_count = to_unsigned(157, 8) ) ELSE
                        coeff159 WHEN ( cur_count = to_unsigned(158, 8) ) ELSE
                        coeff160 WHEN ( cur_count = to_unsigned(159, 8) ) ELSE
                        coeff161 WHEN ( cur_count = to_unsigned(160, 8) ) ELSE
                        coeff162 WHEN ( cur_count = to_unsigned(161, 8) ) ELSE
                        coeff163 WHEN ( cur_count = to_unsigned(162, 8) ) ELSE
                        coeff164 WHEN ( cur_count = to_unsigned(163, 8) ) ELSE
                        coeff165 WHEN ( cur_count = to_unsigned(164, 8) ) ELSE
                        coeff166 WHEN ( cur_count = to_unsigned(165, 8) ) ELSE
                        coeff167 WHEN ( cur_count = to_unsigned(166, 8) ) ELSE
                        coeff168 WHEN ( cur_count = to_unsigned(167, 8) ) ELSE
                        coeff169 WHEN ( cur_count = to_unsigned(168, 8) ) ELSE
                        coeff170 WHEN ( cur_count = to_unsigned(169, 8) ) ELSE
                        coeff171 WHEN ( cur_count = to_unsigned(170, 8) ) ELSE
                        coeff172 WHEN ( cur_count = to_unsigned(171, 8) ) ELSE
                        coeff173 WHEN ( cur_count = to_unsigned(172, 8) ) ELSE
                        coeff174 WHEN ( cur_count = to_unsigned(173, 8) ) ELSE
                        coeff175 WHEN ( cur_count = to_unsigned(174, 8) ) ELSE
                        coeff176 WHEN ( cur_count = to_unsigned(175, 8) ) ELSE
                        coeff177 WHEN ( cur_count = to_unsigned(176, 8) ) ELSE
                        coeff178 WHEN ( cur_count = to_unsigned(177, 8) ) ELSE
                        coeff179 WHEN ( cur_count = to_unsigned(178, 8) ) ELSE
                        coeff180 WHEN ( cur_count = to_unsigned(179, 8) ) ELSE
                        coeff181 WHEN ( cur_count = to_unsigned(180, 8) ) ELSE
                        coeff182 WHEN ( cur_count = to_unsigned(181, 8) ) ELSE
                        coeff183 WHEN ( cur_count = to_unsigned(182, 8) ) ELSE
                        coeff184 WHEN ( cur_count = to_unsigned(183, 8) ) ELSE
                        coeff185 WHEN ( cur_count = to_unsigned(184, 8) ) ELSE
                        coeff186 WHEN ( cur_count = to_unsigned(185, 8) ) ELSE
                        coeff187 WHEN ( cur_count = to_unsigned(186, 8) ) ELSE
                        coeff188 WHEN ( cur_count = to_unsigned(187, 8) ) ELSE
                        coeff189 WHEN ( cur_count = to_unsigned(188, 8) ) ELSE
                        coeff190 WHEN ( cur_count = to_unsigned(189, 8) ) ELSE
                        coeff191 WHEN ( cur_count = to_unsigned(190, 8) ) ELSE
                        coeff192 WHEN ( cur_count = to_unsigned(191, 8) ) ELSE
                        coeff193 WHEN ( cur_count = to_unsigned(192, 8) ) ELSE
                        coeff194 WHEN ( cur_count = to_unsigned(193, 8) ) ELSE
                        coeff195 WHEN ( cur_count = to_unsigned(194, 8) ) ELSE
                        coeff196 WHEN ( cur_count = to_unsigned(195, 8) ) ELSE
                        coeff197 WHEN ( cur_count = to_unsigned(196, 8) ) ELSE
                        coeff198 WHEN ( cur_count = to_unsigned(197, 8) ) ELSE
                        coeff199 WHEN ( cur_count = to_unsigned(198, 8) ) ELSE
                        coeff200 WHEN ( cur_count = to_unsigned(199, 8) ) ELSE
                        coeff201 WHEN ( cur_count = to_unsigned(200, 8) ) ELSE
                        coeff202 WHEN ( cur_count = to_unsigned(201, 8) ) ELSE
                        coeff203 WHEN ( cur_count = to_unsigned(202, 8) ) ELSE
                        coeff204 WHEN ( cur_count = to_unsigned(203, 8) ) ELSE
                        coeff205 WHEN ( cur_count = to_unsigned(204, 8) ) ELSE
                        coeff206 WHEN ( cur_count = to_unsigned(205, 8) ) ELSE
                        coeff207 WHEN ( cur_count = to_unsigned(206, 8) ) ELSE
                        coeff208 WHEN ( cur_count = to_unsigned(207, 8) ) ELSE
                        coeff209 WHEN ( cur_count = to_unsigned(208, 8) ) ELSE
                        coeff210 WHEN ( cur_count = to_unsigned(209, 8) ) ELSE
                        coeff211 WHEN ( cur_count = to_unsigned(210, 8) ) ELSE
                        coeff212 WHEN ( cur_count = to_unsigned(211, 8) ) ELSE
                        coeff213 WHEN ( cur_count = to_unsigned(212, 8) ) ELSE
                        coeff214 WHEN ( cur_count = to_unsigned(213, 8) ) ELSE
                        coeff215 WHEN ( cur_count = to_unsigned(214, 8) ) ELSE
                        coeff216 WHEN ( cur_count = to_unsigned(215, 8) ) ELSE
                        coeff217 WHEN ( cur_count = to_unsigned(216, 8) ) ELSE
                        coeff218 WHEN ( cur_count = to_unsigned(217, 8) ) ELSE
                        coeff219 WHEN ( cur_count = to_unsigned(218, 8) ) ELSE
                        coeff220 WHEN ( cur_count = to_unsigned(219, 8) ) ELSE
                        coeff221 WHEN ( cur_count = to_unsigned(220, 8) ) ELSE
                        coeff222 WHEN ( cur_count = to_unsigned(221, 8) ) ELSE
                        coeff223 WHEN ( cur_count = to_unsigned(222, 8) ) ELSE
                        coeff224 WHEN ( cur_count = to_unsigned(223, 8) ) ELSE
                        coeff225 WHEN ( cur_count = to_unsigned(224, 8) ) ELSE
                        coeff226 WHEN ( cur_count = to_unsigned(225, 8) ) ELSE
                        coeff227 WHEN ( cur_count = to_unsigned(226, 8) ) ELSE
                        coeff228 WHEN ( cur_count = to_unsigned(227, 8) ) ELSE
                        coeff229 WHEN ( cur_count = to_unsigned(228, 8) ) ELSE
                        coeff230 WHEN ( cur_count = to_unsigned(229, 8) ) ELSE
                        coeff231 WHEN ( cur_count = to_unsigned(230, 8) ) ELSE
                        coeff232 WHEN ( cur_count = to_unsigned(231, 8) ) ELSE
                        coeff233 WHEN ( cur_count = to_unsigned(232, 8) ) ELSE
                        coeff234 WHEN ( cur_count = to_unsigned(233, 8) ) ELSE
                        coeff235 WHEN ( cur_count = to_unsigned(234, 8) ) ELSE
                        coeff236 WHEN ( cur_count = to_unsigned(235, 8) ) ELSE
                        coeff237 WHEN ( cur_count = to_unsigned(236, 8) ) ELSE
                        coeff238 WHEN ( cur_count = to_unsigned(237, 8) ) ELSE
                        coeff239 WHEN ( cur_count = to_unsigned(238, 8) ) ELSE
                        coeff240 WHEN ( cur_count = to_unsigned(239, 8) ) ELSE
                        coeff241 WHEN ( cur_count = to_unsigned(240, 8) ) ELSE
                        coeff242 WHEN ( cur_count = to_unsigned(241, 8) ) ELSE
                        coeff243 WHEN ( cur_count = to_unsigned(242, 8) ) ELSE
                        coeff244 WHEN ( cur_count = to_unsigned(243, 8) ) ELSE
                        coeff245 WHEN ( cur_count = to_unsigned(244, 8) ) ELSE
                        coeff246 WHEN ( cur_count = to_unsigned(245, 8) ) ELSE
                        coeff247 WHEN ( cur_count = to_unsigned(246, 8) ) ELSE
                        coeff248 WHEN ( cur_count = to_unsigned(247, 8) ) ELSE
                        coeff249 WHEN ( cur_count = to_unsigned(248, 8) ) ELSE
                        coeff250 WHEN ( cur_count = to_unsigned(249, 8) ) ELSE
                        coeff251 WHEN ( cur_count = to_unsigned(250, 8) ) ELSE
                        coeff252 WHEN ( cur_count = to_unsigned(251, 8) ) ELSE
                        coeff253 WHEN ( cur_count = to_unsigned(252, 8) ) ELSE
                        coeff254 WHEN ( cur_count = to_unsigned(253, 8) ) ELSE
                        coeff255 WHEN ( cur_count = to_unsigned(254, 8) ) ELSE
                        coeff256;
  mul_temp <= inputmux_1 * product_1_mux;
  product_1 <= resize(shift_right(mul_temp(31) & mul_temp(31 DOWNTO 0) + ( "0" & (mul_temp(1))), 1), 32);

  prod_typeconvert_1 <= resize(product_1, 40);

  add_temp <= resize(prod_typeconvert_1, 41) + resize(acc_out_1, 41);
  acc_sum_1 <= add_temp(39 DOWNTO 0);

  acc_in_1 <= prod_typeconvert_1 WHEN ( phase_0 = '1' ) ELSE
                   acc_sum_1;

  Acc_reg_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      acc_out_1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        acc_out_1 <= acc_in_1;
      END IF;
    END IF; 
  END PROCESS Acc_reg_1_process;

  Finalsum_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      acc_final <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        acc_final <= acc_out_1;
      END IF;
    END IF; 
  END PROCESS Finalsum_reg_process;

  output_typeconvert <= resize(shift_right(acc_final(29 DOWNTO 0) + ( "0" & (acc_final(14) & NOT acc_final(14) & NOT acc_final(14) & NOT acc_final(14) & NOT acc_final(14) & NOT acc_final(14) & NOT acc_final(14) & NOT acc_final(14) & NOT acc_final(14) & NOT acc_final(14) & NOT acc_final(14) & NOT acc_final(14) & NOT acc_final(14) & NOT acc_final(14))), 14), 16);

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_255 = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
