-- -------------------------------------------------------------
--
-- Module: tx_cic
-- Generated by MATLAB(R) 9.6 and Filter Design HDL Coder 3.1.5.
-- Generated on: 2019-04-13 17:32:00
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- OptimizeForHDL: on
-- EDAScriptGeneration: off
-- Name: tx_cic
-- TestBenchName: tx_cic_tb
-- TestBenchStimulus: step ramp chirp noise 
-- GenerateHDLTestBench: off

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Multirate Filter (real)
-- -----------------------------------------
-- Filter Structure      : Cascaded Integrator-Comb Interpolator
-- Interpolation Factor  : 512
-- Differential Delay    : 1
-- Number of Sections    : 5
-- Stable                : Yes
-- Linear Phase          : Yes (Type 2)
--
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY tx_cic IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(15 DOWNTO 0); -- sfix16_En15
         filter_out                      :   OUT   std_logic_vector(13 DOWNTO 0); -- sfix14_E23
         ce_out                          :   OUT   std_logic  
         );

END tx_cic;


----------------------------------------------------------------
--Module Architecture: tx_cic
----------------------------------------------------------------
ARCHITECTURE rtl OF tx_cic IS
  -- Local Functions
  -- Type Definitions
  -- Constants
  CONSTANT zeroconst                      : signed(59 DOWNTO 0) := to_signed(0, 60); -- sfix60_En55
  -- Signals
  SIGNAL cur_count                        : unsigned(8 DOWNTO 0); -- ufix9
  SIGNAL phase_0                          : std_logic; -- boolean
  --   
  SIGNAL input_register                   : signed(15 DOWNTO 0); -- sfix16_En15
  --   -- Section 1 Signals 
  SIGNAL section_in1                      : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL section_cast1                    : signed(59 DOWNTO 0); -- sfix60_En58
  SIGNAL diff1                            : signed(59 DOWNTO 0); -- sfix60_En58
  SIGNAL section_out1                     : signed(59 DOWNTO 0); -- sfix60_En58
  SIGNAL sub_cast                         : signed(59 DOWNTO 0); -- sfix60_En58
  SIGNAL sub_cast_1                       : signed(59 DOWNTO 0); -- sfix60_En58
  SIGNAL sub_temp                         : signed(60 DOWNTO 0); -- sfix61_En58
  --   -- Section 2 Signals 
  SIGNAL section_in2                      : signed(59 DOWNTO 0); -- sfix60_En58
  SIGNAL section_cast2                    : signed(59 DOWNTO 0); -- sfix60_En57
  SIGNAL diff2                            : signed(59 DOWNTO 0); -- sfix60_En57
  SIGNAL section_out2                     : signed(59 DOWNTO 0); -- sfix60_En57
  SIGNAL sub_cast_2                       : signed(59 DOWNTO 0); -- sfix60_En57
  SIGNAL sub_cast_3                       : signed(59 DOWNTO 0); -- sfix60_En57
  SIGNAL sub_temp_1                       : signed(60 DOWNTO 0); -- sfix61_En57
  --   -- Section 3 Signals 
  SIGNAL section_in3                      : signed(59 DOWNTO 0); -- sfix60_En57
  SIGNAL section_cast3                    : signed(59 DOWNTO 0); -- sfix60_En56
  SIGNAL diff3                            : signed(59 DOWNTO 0); -- sfix60_En56
  SIGNAL section_out3                     : signed(59 DOWNTO 0); -- sfix60_En56
  SIGNAL sub_cast_4                       : signed(59 DOWNTO 0); -- sfix60_En56
  SIGNAL sub_cast_5                       : signed(59 DOWNTO 0); -- sfix60_En56
  SIGNAL sub_temp_2                       : signed(60 DOWNTO 0); -- sfix61_En56
  --   -- Section 4 Signals 
  SIGNAL section_in4                      : signed(59 DOWNTO 0); -- sfix60_En56
  SIGNAL section_cast4                    : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL diff4                            : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL section_out4                     : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL sub_cast_6                       : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL sub_cast_7                       : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL sub_temp_3                       : signed(60 DOWNTO 0); -- sfix61_En55
  --   -- Section 5 Signals 
  SIGNAL section_in5                      : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL diff5                            : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL section_out5                     : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL sub_cast_8                       : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL sub_cast_9                       : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL sub_temp_4                       : signed(60 DOWNTO 0); -- sfix61_En55
  SIGNAL upsampling                       : signed(59 DOWNTO 0); -- sfix60_En55
  --   -- Section 6 Signals 
  SIGNAL section_in6                      : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL sum1                             : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL section_out6                     : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL add_cast                         : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL add_cast_1                       : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL add_temp                         : signed(60 DOWNTO 0); -- sfix61_En55
  --   -- Section 7 Signals 
  SIGNAL section_in7                      : signed(59 DOWNTO 0); -- sfix60_En55
  SIGNAL section_cast7                    : signed(59 DOWNTO 0); -- sfix60_En47
  SIGNAL sum2                             : signed(59 DOWNTO 0); -- sfix60_En47
  SIGNAL section_out7                     : signed(59 DOWNTO 0); -- sfix60_En47
  SIGNAL add_cast_2                       : signed(59 DOWNTO 0); -- sfix60_En47
  SIGNAL add_cast_3                       : signed(59 DOWNTO 0); -- sfix60_En47
  SIGNAL add_temp_1                       : signed(60 DOWNTO 0); -- sfix61_En47
  --   -- Section 8 Signals 
  SIGNAL section_in8                      : signed(59 DOWNTO 0); -- sfix60_En47
  SIGNAL section_cast8                    : signed(59 DOWNTO 0); -- sfix60_En39
  SIGNAL sum3                             : signed(59 DOWNTO 0); -- sfix60_En39
  SIGNAL section_out8                     : signed(59 DOWNTO 0); -- sfix60_En39
  SIGNAL add_cast_4                       : signed(59 DOWNTO 0); -- sfix60_En39
  SIGNAL add_cast_5                       : signed(59 DOWNTO 0); -- sfix60_En39
  SIGNAL add_temp_2                       : signed(60 DOWNTO 0); -- sfix61_En39
  --   -- Section 9 Signals 
  SIGNAL section_in9                      : signed(59 DOWNTO 0); -- sfix60_En39
  SIGNAL section_cast9                    : signed(59 DOWNTO 0); -- sfix60_En31
  SIGNAL sum4                             : signed(59 DOWNTO 0); -- sfix60_En31
  SIGNAL section_out9                     : signed(59 DOWNTO 0); -- sfix60_En31
  SIGNAL add_cast_6                       : signed(59 DOWNTO 0); -- sfix60_En31
  SIGNAL add_cast_7                       : signed(59 DOWNTO 0); -- sfix60_En31
  SIGNAL add_temp_3                       : signed(60 DOWNTO 0); -- sfix61_En31
  --   -- Section 10 Signals 
  SIGNAL section_in10                     : signed(59 DOWNTO 0); -- sfix60_En31
  SIGNAL section_cast10                   : signed(59 DOWNTO 0); -- sfix60_En23
  SIGNAL sum5                             : signed(59 DOWNTO 0); -- sfix60_En23
  SIGNAL section_out10                    : signed(59 DOWNTO 0); -- sfix60_En23
  SIGNAL add_cast_8                       : signed(59 DOWNTO 0); -- sfix60_En23
  SIGNAL add_cast_9                       : signed(59 DOWNTO 0); -- sfix60_En23
  SIGNAL add_temp_4                       : signed(60 DOWNTO 0); -- sfix61_En23
  SIGNAL output_typeconvert               : signed(13 DOWNTO 0); -- sfix14_E23
  --   
  SIGNAL output_register                  : signed(13 DOWNTO 0); -- sfix14_E23


BEGIN

  -- Block Statements
  --   ------------------ CE Output Generation ------------------

  ce_output : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cur_count <= to_unsigned(0, 9);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF cur_count >= to_unsigned(511, 9) THEN
          cur_count <= to_unsigned(0, 9);
        ELSE
          cur_count <= cur_count + to_unsigned(1, 9);
        END IF;
      END IF;
    END IF; 
  END PROCESS ce_output;

  phase_0 <= '1' WHEN cur_count = to_unsigned(0, 9) AND clk_enable = '1' ELSE '0';

  --   ------------------ Input Register ------------------

  input_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        input_register <= signed(filter_in);
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  --   ------------------ Section # 1 : Comb ------------------

  section_in1 <= input_register;

  section_cast1 <= resize(section_in1(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 60);

  sub_cast <= section_cast1;
  sub_cast_1 <= diff1;
  sub_temp <= resize(sub_cast, 61) - resize(sub_cast_1, 61);
  section_out1 <= sub_temp(59 DOWNTO 0);

  comb_delay_section1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      diff1 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        diff1 <= section_cast1;
      END IF;
    END IF; 
  END PROCESS comb_delay_section1;

  --   ------------------ Section # 2 : Comb ------------------

  section_in2 <= section_out1;

  section_cast2 <= resize(section_in2(59 DOWNTO 1), 60);

  sub_cast_2 <= section_cast2;
  sub_cast_3 <= diff2;
  sub_temp_1 <= resize(sub_cast_2, 61) - resize(sub_cast_3, 61);
  section_out2 <= sub_temp_1(59 DOWNTO 0);

  comb_delay_section2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      diff2 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        diff2 <= section_cast2;
      END IF;
    END IF; 
  END PROCESS comb_delay_section2;

  --   ------------------ Section # 3 : Comb ------------------

  section_in3 <= section_out2;

  section_cast3 <= resize(section_in3(59 DOWNTO 1), 60);

  sub_cast_4 <= section_cast3;
  sub_cast_5 <= diff3;
  sub_temp_2 <= resize(sub_cast_4, 61) - resize(sub_cast_5, 61);
  section_out3 <= sub_temp_2(59 DOWNTO 0);

  comb_delay_section3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      diff3 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        diff3 <= section_cast3;
      END IF;
    END IF; 
  END PROCESS comb_delay_section3;

  --   ------------------ Section # 4 : Comb ------------------

  section_in4 <= section_out3;

  section_cast4 <= resize(section_in4(59 DOWNTO 1), 60);

  sub_cast_6 <= section_cast4;
  sub_cast_7 <= diff4;
  sub_temp_3 <= resize(sub_cast_6, 61) - resize(sub_cast_7, 61);
  section_out4 <= sub_temp_3(59 DOWNTO 0);

  comb_delay_section4 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      diff4 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        diff4 <= section_cast4;
      END IF;
    END IF; 
  END PROCESS comb_delay_section4;

  --   ------------------ Section # 5 : Comb ------------------

  section_in5 <= section_out4;

  sub_cast_8 <= section_in5;
  sub_cast_9 <= diff5;
  sub_temp_4 <= resize(sub_cast_8, 61) - resize(sub_cast_9, 61);
  section_out5 <= sub_temp_4(59 DOWNTO 0);

  comb_delay_section5 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      diff5 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF phase_0 = '1' THEN
        diff5 <= section_in5;
      END IF;
    END IF; 
  END PROCESS comb_delay_section5;

  upsampling <= section_out5 WHEN ( phase_0 = '1' ) ELSE
                zeroconst;
  --   ------------------ Section # 6 : Integrator ------------------

  section_in6 <= upsampling;

  add_cast <= section_in6;
  add_cast_1 <= section_out6;
  add_temp <= resize(add_cast, 61) + resize(add_cast_1, 61);
  sum1 <= add_temp(59 DOWNTO 0);

  integrator_delay_section6 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      section_out6 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        section_out6 <= sum1;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section6;

  --   ------------------ Section # 7 : Integrator ------------------

  section_in7 <= section_out6;

  section_cast7 <= resize(section_in7(59 DOWNTO 8), 60);

  add_cast_2 <= section_cast7;
  add_cast_3 <= section_out7;
  add_temp_1 <= resize(add_cast_2, 61) + resize(add_cast_3, 61);
  sum2 <= add_temp_1(59 DOWNTO 0);

  integrator_delay_section7 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      section_out7 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        section_out7 <= sum2;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section7;

  --   ------------------ Section # 8 : Integrator ------------------

  section_in8 <= section_out7;

  section_cast8 <= resize(section_in8(59 DOWNTO 8), 60);

  add_cast_4 <= section_cast8;
  add_cast_5 <= section_out8;
  add_temp_2 <= resize(add_cast_4, 61) + resize(add_cast_5, 61);
  sum3 <= add_temp_2(59 DOWNTO 0);

  integrator_delay_section8 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      section_out8 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        section_out8 <= sum3;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section8;

  --   ------------------ Section # 9 : Integrator ------------------

  section_in9 <= section_out8;

  section_cast9 <= resize(section_in9(59 DOWNTO 8), 60);

  add_cast_6 <= section_cast9;
  add_cast_7 <= section_out9;
  add_temp_3 <= resize(add_cast_6, 61) + resize(add_cast_7, 61);
  sum4 <= add_temp_3(59 DOWNTO 0);

  integrator_delay_section9 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      section_out9 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        section_out9 <= sum4;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section9;

  --   ------------------ Section # 10 : Integrator ------------------

  section_in10 <= section_out9;

  section_cast10 <= resize(section_in10(59 DOWNTO 8), 60);

  add_cast_8 <= section_cast10;
  add_cast_9 <= section_out10;
  add_temp_4 <= resize(add_cast_8, 61) + resize(add_cast_9, 61);
  sum5 <= add_temp_4(59 DOWNTO 0);

  integrator_delay_section10 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      section_out10 <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        section_out10 <= sum5;
      END IF;
    END IF; 
  END PROCESS integrator_delay_section10;

  output_typeconvert <= section_out10(59 DOWNTO 46);

  --   ------------------ Output Register ------------------

  output_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS output_reg_process;

  -- Assignment Statements
  ce_out <= phase_0;
  filter_out <= std_logic_vector(output_register);
END rtl;
