// -------------------------------------------------------------
//
// Module: tx_ciccomp
// Generated by MATLAB(R) 9.4 and Filter Design HDL Coder 3.1.3.
// Generated on: 2018-10-27 22:07:06
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// OptimizeForHDL: on
// EDAScriptGeneration: off
// Name: tx_ciccomp
// SerialPartition: 48
// TargetLanguage: Verilog
// TestBenchName: tx_ciccomp_tb
// TestBenchStimulus: impulse step ramp chirp noise 
// GenerateHDLTestBench: off

// Filter Specifications:
//
// Sample Rate            : N/A (normalized frequency)
// Response               : CIC Compensator
// Specification          : Fp,Fst,Ap,Ast
// Number of Sections     : 6
// Differential Delay     : 1
// CIC Rate Change Factor : 1000
// Stopband Edge          : 0.55
// Passband Edge          : 0.45
// Stopband Atten.        : 60 dB
// Passband Ripple        : 1 dB
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully Serial
// Folding Factor        : 48
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 48
// Stable            : Yes
// Linear Phase      : Yes (Type 2)
// Arithmetic        : fixed
// Numerator         : s16,15 -> [-1 1)
// Input             : s16,15 -> [-1 1)
// Filter Internals  : Specify Precision
//   Output          : s16,15 -> [-1 1)
//   Product         : s32,29 -> [-4 4)
//   Accumulator     : s40,29 -> [-1024 1024)
//   Round Mode      : convergent
//   Overflow Mode   : wrap
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module tx_ciccomp
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16_En15
  output  signed [15:0] filter_out; //sfix16_En15

////////////////////////////////////////////////////////////////
//Module Architecture: tx_ciccomp
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b0000000010110001; //sfix16_En15
  parameter signed [15:0] coeff2 = 16'b0000000111100010; //sfix16_En15
  parameter signed [15:0] coeff3 = 16'b0000000111001101; //sfix16_En15
  parameter signed [15:0] coeff4 = 16'b1111111111000010; //sfix16_En15
  parameter signed [15:0] coeff5 = 16'b1111111001100010; //sfix16_En15
  parameter signed [15:0] coeff6 = 16'b0000000000011011; //sfix16_En15
  parameter signed [15:0] coeff7 = 16'b0000001000000010; //sfix16_En15
  parameter signed [15:0] coeff8 = 16'b0000000000100010; //sfix16_En15
  parameter signed [15:0] coeff9 = 16'b1111110101011111; //sfix16_En15
  parameter signed [15:0] coeff10 = 16'b1111111101111100; //sfix16_En15
  parameter signed [15:0] coeff11 = 16'b0000001101100110; //sfix16_En15
  parameter signed [15:0] coeff12 = 16'b0000000100100010; //sfix16_En15
  parameter signed [15:0] coeff13 = 16'b1111101110100010; //sfix16_En15
  parameter signed [15:0] coeff14 = 16'b1111110111101111; //sfix16_En15
  parameter signed [15:0] coeff15 = 16'b0000010110010010; //sfix16_En15
  parameter signed [15:0] coeff16 = 16'b0000001110000100; //sfix16_En15
  parameter signed [15:0] coeff17 = 16'b1111100011011000; //sfix16_En15
  parameter signed [15:0] coeff18 = 16'b1111101000011100; //sfix16_En15
  parameter signed [15:0] coeff19 = 16'b0000100101100000; //sfix16_En15
  parameter signed [15:0] coeff20 = 16'b0000101001011100; //sfix16_En15
  parameter signed [15:0] coeff21 = 16'b1111001100110010; //sfix16_En15
  parameter signed [15:0] coeff22 = 16'b1110101011000000; //sfix16_En15
  parameter signed [15:0] coeff23 = 16'b0001000110011001; //sfix16_En15
  parameter signed [15:0] coeff24 = 16'b0100010001110100; //sfix16_En15
  parameter signed [15:0] coeff25 = 16'b0100010001110100; //sfix16_En15
  parameter signed [15:0] coeff26 = 16'b0001000110011001; //sfix16_En15
  parameter signed [15:0] coeff27 = 16'b1110101011000000; //sfix16_En15
  parameter signed [15:0] coeff28 = 16'b1111001100110010; //sfix16_En15
  parameter signed [15:0] coeff29 = 16'b0000101001011100; //sfix16_En15
  parameter signed [15:0] coeff30 = 16'b0000100101100000; //sfix16_En15
  parameter signed [15:0] coeff31 = 16'b1111101000011100; //sfix16_En15
  parameter signed [15:0] coeff32 = 16'b1111100011011000; //sfix16_En15
  parameter signed [15:0] coeff33 = 16'b0000001110000100; //sfix16_En15
  parameter signed [15:0] coeff34 = 16'b0000010110010010; //sfix16_En15
  parameter signed [15:0] coeff35 = 16'b1111110111101111; //sfix16_En15
  parameter signed [15:0] coeff36 = 16'b1111101110100010; //sfix16_En15
  parameter signed [15:0] coeff37 = 16'b0000000100100010; //sfix16_En15
  parameter signed [15:0] coeff38 = 16'b0000001101100110; //sfix16_En15
  parameter signed [15:0] coeff39 = 16'b1111111101111100; //sfix16_En15
  parameter signed [15:0] coeff40 = 16'b1111110101011111; //sfix16_En15
  parameter signed [15:0] coeff41 = 16'b0000000000100010; //sfix16_En15
  parameter signed [15:0] coeff42 = 16'b0000001000000010; //sfix16_En15
  parameter signed [15:0] coeff43 = 16'b0000000000011011; //sfix16_En15
  parameter signed [15:0] coeff44 = 16'b1111111001100010; //sfix16_En15
  parameter signed [15:0] coeff45 = 16'b1111111111000010; //sfix16_En15
  parameter signed [15:0] coeff46 = 16'b0000000111001101; //sfix16_En15
  parameter signed [15:0] coeff47 = 16'b0000000111100010; //sfix16_En15
  parameter signed [15:0] coeff48 = 16'b0000000010110001; //sfix16_En15

  // Signals
  reg  [5:0] cur_count; // ufix6
  wire phase_47; // boolean
  wire phase_0; // boolean
  reg  signed [15:0] delay_pipeline [0:47] ; // sfix16_En15
  wire signed [15:0] inputmux_1; // sfix16_En15
  reg  signed [39:0] acc_final; // sfix40_En29
  reg  signed [39:0] acc_out_1; // sfix40_En29
  wire signed [31:0] product_1; // sfix32_En29
  wire signed [15:0] product_1_mux; // sfix16_En15
  wire signed [31:0] mul_temp; // sfix32_En30
  wire signed [39:0] prod_typeconvert_1; // sfix40_En29
  wire signed [39:0] acc_sum_1; // sfix40_En29
  wire signed [39:0] acc_in_1; // sfix40_En29
  wire signed [39:0] add_signext; // sfix40_En29
  wire signed [39:0] add_signext_1; // sfix40_En29
  wire signed [40:0] add_temp; // sfix41_En29
  wire signed [15:0] output_typeconvert; // sfix16_En15
  reg  signed [15:0] output_register; // sfix16_En15

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: Counter_process
      if (reset == 1'b1) begin
        cur_count <= 6'b101111;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count >= 6'b101111) begin
            cur_count <= 6'b000000;
          end
          else begin
            cur_count <= cur_count + 6'b000001;
          end
        end
      end
    end // Counter_process

  assign  phase_47 = (cur_count == 6'b101111 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_0 = (cur_count == 6'b000000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
        delay_pipeline[41] <= 0;
        delay_pipeline[42] <= 0;
        delay_pipeline[43] <= 0;
        delay_pipeline[44] <= 0;
        delay_pipeline[45] <= 0;
        delay_pipeline[46] <= 0;
        delay_pipeline[47] <= 0;
      end
      else begin
        if (phase_47 == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
          delay_pipeline[41] <= delay_pipeline[40];
          delay_pipeline[42] <= delay_pipeline[41];
          delay_pipeline[43] <= delay_pipeline[42];
          delay_pipeline[44] <= delay_pipeline[43];
          delay_pipeline[45] <= delay_pipeline[44];
          delay_pipeline[46] <= delay_pipeline[45];
          delay_pipeline[47] <= delay_pipeline[46];
        end
      end
    end // Delay_Pipeline_process


  assign inputmux_1 = (cur_count == 6'b000000) ? delay_pipeline[0] :
                     (cur_count == 6'b000001) ? delay_pipeline[1] :
                     (cur_count == 6'b000010) ? delay_pipeline[2] :
                     (cur_count == 6'b000011) ? delay_pipeline[3] :
                     (cur_count == 6'b000100) ? delay_pipeline[4] :
                     (cur_count == 6'b000101) ? delay_pipeline[5] :
                     (cur_count == 6'b000110) ? delay_pipeline[6] :
                     (cur_count == 6'b000111) ? delay_pipeline[7] :
                     (cur_count == 6'b001000) ? delay_pipeline[8] :
                     (cur_count == 6'b001001) ? delay_pipeline[9] :
                     (cur_count == 6'b001010) ? delay_pipeline[10] :
                     (cur_count == 6'b001011) ? delay_pipeline[11] :
                     (cur_count == 6'b001100) ? delay_pipeline[12] :
                     (cur_count == 6'b001101) ? delay_pipeline[13] :
                     (cur_count == 6'b001110) ? delay_pipeline[14] :
                     (cur_count == 6'b001111) ? delay_pipeline[15] :
                     (cur_count == 6'b010000) ? delay_pipeline[16] :
                     (cur_count == 6'b010001) ? delay_pipeline[17] :
                     (cur_count == 6'b010010) ? delay_pipeline[18] :
                     (cur_count == 6'b010011) ? delay_pipeline[19] :
                     (cur_count == 6'b010100) ? delay_pipeline[20] :
                     (cur_count == 6'b010101) ? delay_pipeline[21] :
                     (cur_count == 6'b010110) ? delay_pipeline[22] :
                     (cur_count == 6'b010111) ? delay_pipeline[23] :
                     (cur_count == 6'b011000) ? delay_pipeline[24] :
                     (cur_count == 6'b011001) ? delay_pipeline[25] :
                     (cur_count == 6'b011010) ? delay_pipeline[26] :
                     (cur_count == 6'b011011) ? delay_pipeline[27] :
                     (cur_count == 6'b011100) ? delay_pipeline[28] :
                     (cur_count == 6'b011101) ? delay_pipeline[29] :
                     (cur_count == 6'b011110) ? delay_pipeline[30] :
                     (cur_count == 6'b011111) ? delay_pipeline[31] :
                     (cur_count == 6'b100000) ? delay_pipeline[32] :
                     (cur_count == 6'b100001) ? delay_pipeline[33] :
                     (cur_count == 6'b100010) ? delay_pipeline[34] :
                     (cur_count == 6'b100011) ? delay_pipeline[35] :
                     (cur_count == 6'b100100) ? delay_pipeline[36] :
                     (cur_count == 6'b100101) ? delay_pipeline[37] :
                     (cur_count == 6'b100110) ? delay_pipeline[38] :
                     (cur_count == 6'b100111) ? delay_pipeline[39] :
                     (cur_count == 6'b101000) ? delay_pipeline[40] :
                     (cur_count == 6'b101001) ? delay_pipeline[41] :
                     (cur_count == 6'b101010) ? delay_pipeline[42] :
                     (cur_count == 6'b101011) ? delay_pipeline[43] :
                     (cur_count == 6'b101100) ? delay_pipeline[44] :
                     (cur_count == 6'b101101) ? delay_pipeline[45] :
                     (cur_count == 6'b101110) ? delay_pipeline[46] :
                     delay_pipeline[47];

  //   ------------------ Serial partition # 1 ------------------

  assign product_1_mux = (cur_count == 6'b000000) ? coeff1 :
                        (cur_count == 6'b000001) ? coeff2 :
                        (cur_count == 6'b000010) ? coeff3 :
                        (cur_count == 6'b000011) ? coeff4 :
                        (cur_count == 6'b000100) ? coeff5 :
                        (cur_count == 6'b000101) ? coeff6 :
                        (cur_count == 6'b000110) ? coeff7 :
                        (cur_count == 6'b000111) ? coeff8 :
                        (cur_count == 6'b001000) ? coeff9 :
                        (cur_count == 6'b001001) ? coeff10 :
                        (cur_count == 6'b001010) ? coeff11 :
                        (cur_count == 6'b001011) ? coeff12 :
                        (cur_count == 6'b001100) ? coeff13 :
                        (cur_count == 6'b001101) ? coeff14 :
                        (cur_count == 6'b001110) ? coeff15 :
                        (cur_count == 6'b001111) ? coeff16 :
                        (cur_count == 6'b010000) ? coeff17 :
                        (cur_count == 6'b010001) ? coeff18 :
                        (cur_count == 6'b010010) ? coeff19 :
                        (cur_count == 6'b010011) ? coeff20 :
                        (cur_count == 6'b010100) ? coeff21 :
                        (cur_count == 6'b010101) ? coeff22 :
                        (cur_count == 6'b010110) ? coeff23 :
                        (cur_count == 6'b010111) ? coeff24 :
                        (cur_count == 6'b011000) ? coeff25 :
                        (cur_count == 6'b011001) ? coeff26 :
                        (cur_count == 6'b011010) ? coeff27 :
                        (cur_count == 6'b011011) ? coeff28 :
                        (cur_count == 6'b011100) ? coeff29 :
                        (cur_count == 6'b011101) ? coeff30 :
                        (cur_count == 6'b011110) ? coeff31 :
                        (cur_count == 6'b011111) ? coeff32 :
                        (cur_count == 6'b100000) ? coeff33 :
                        (cur_count == 6'b100001) ? coeff34 :
                        (cur_count == 6'b100010) ? coeff35 :
                        (cur_count == 6'b100011) ? coeff36 :
                        (cur_count == 6'b100100) ? coeff37 :
                        (cur_count == 6'b100101) ? coeff38 :
                        (cur_count == 6'b100110) ? coeff39 :
                        (cur_count == 6'b100111) ? coeff40 :
                        (cur_count == 6'b101000) ? coeff41 :
                        (cur_count == 6'b101001) ? coeff42 :
                        (cur_count == 6'b101010) ? coeff43 :
                        (cur_count == 6'b101011) ? coeff44 :
                        (cur_count == 6'b101100) ? coeff45 :
                        (cur_count == 6'b101101) ? coeff46 :
                        (cur_count == 6'b101110) ? coeff47 :
                        coeff48;
  assign mul_temp = inputmux_1 * product_1_mux;
  assign product_1 = ({{1{mul_temp[31]}}, mul_temp[31:0]} + mul_temp[1])>>>1;

  assign prod_typeconvert_1 = $signed({{8{product_1[31]}}, product_1});

  assign add_signext = prod_typeconvert_1;
  assign add_signext_1 = acc_out_1;
  assign add_temp = add_signext + add_signext_1;
  assign acc_sum_1 = add_temp[39:0];

  assign acc_in_1 = (phase_0 == 1'b1) ? prod_typeconvert_1 :
                   acc_sum_1;

  always @ (posedge clk or posedge reset)
    begin: Acc_reg_1_process
      if (reset == 1'b1) begin
        acc_out_1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          acc_out_1 <= acc_in_1;
        end
      end
    end // Acc_reg_1_process

  always @ (posedge clk or posedge reset)
    begin: Finalsum_reg_process
      if (reset == 1'b1) begin
        acc_final <= 0;
      end
      else begin
        if (phase_0 == 1'b1) begin
          acc_final <= acc_out_1;
        end
      end
    end // Finalsum_reg_process

  assign output_typeconvert = (acc_final[29:0] + {acc_final[14], {13{~acc_final[14]}}})>>>14;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (phase_47 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // tx_ciccomp
